version: "3.8"
services:
  vpn:
    image: ghcr.io/bubuntux/nordlynx 
    cap_add:
      - NET_ADMIN
      - NET_RAW
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Oslo
      - CONNECT=Norway
      - TECHNOLOGY=OpenVPN
      - PROTOCOL=UDP
      - KILLSWITCH=on
    env_file:
      - /secrets/torrent-stack.env
    volumes:
      - /mnt/lib_modules:/lib/modules:ro
    ports:
      - "6881:6881" # qbittorrent
      - "6881:6881/udp" # qbittorrent
      - "8080:8080" # qbittorrent
      - "7878:7878" # radarr
      - "8989:8989" # sonarr
      - "8686:8686" # lidarr
      - "9117:9117" # jackett
      - "8191:8191" # flaresolverr
      - "5055:5055" # jellyseerr
    security_opt:
      - apparmor:unconfined

  qbittorrent:
    image: ghcr.io/linuxserver/qbittorrent
    depends_on: [vpn]
    network_mode: "service:vpn"
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - /hdd/media/downloads:/downloads
      - /config/qbittorrent:/config
    security_opt:
      - apparmor:unconfined

  radarr:
    image: ghcr.io/linuxserver/radarr
    depends_on: [vpn]
    network_mode: "service:vpn"
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - /config/radarr:/config
      - /hdd/media/movies:/movies
      - /hdd/media/downloads:/downloads
    security_opt:
      - apparmor:unconfined

  sonarr:
    image: ghcr.io/linuxserver/sonarr
    depends_on: [vpn]
    network_mode: "service:vpn"
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - /config/sonarr:/config
      - /hdd/media/tv:/tv
      - /hdd/media/downloads:/downloads
    security_opt:
      - apparmor:unconfined

  lidarr:
    image: ghcr.io/linuxserver/lidarr
    depends_on: [vpn]
    network_mode: "service:vpn"
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - /config/lidarr:/config
      - /hdd/music:/music
      - /hdd/media/downloads:/downloads
    security_opt:
      - apparmor:unconfined

  jackett:
    image: ghcr.io/linuxserver/jackett
    depends_on: [vpn]
    network_mode: "service:vpn"
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - /config/jackett:/config
      - /hdd/media/downloads:/downloads
    security_opt:
      - apparmor:unconfined

  jellyseerr:
    image: fallenbagel/jellyseerr:latest
    depends_on: [vpn]
    network_mode: "service:vpn"
    environment:
      - LOG_LEVEL=info
      - TZ=Europe/Oslo
      - PORT=5055
    volumes:
      - /config/jellyseerr:/app/config
    security_opt:
      - apparmor:unconfined

  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr:v3.3.16
    depends_on: [vpn]
    network_mode: "service:vpn"
    environment:
      - LOG_LEVEL=debug
      - TZ=Europe/Oslo
      - HOST=0.0.0.0
      - PORT=8191
      - HEADLESS=true
      - BROWSER_TIMEOUT=55000
    security_opt:
      - apparmor:unconfined