---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: diun
  namespace: linole
  labels:
    app: diun
spec:
  replicas: 1
  selector:
    matchLabels:
      app: diun
  template:
    metadata:
      labels:
        app: diun
    spec:
      containers:
        - name: diun
          image: crazymax/diun:latest
          env:
            - name: TZ
              value: "Europe/Oslo"
            - name: LOG_LEVEL
              value: "info"
            - name: LOG_JSON
              value: "false"
          volumeMounts:
            - name: diun-config
              mountPath: /etc/diun/diun.yaml
              subPath: diun.yaml
            - name: diun-config
              mountPath: /etc/diun/image-watch.yaml
              subPath: image-watch.yaml
            - name: diun-data
              mountPath: /data
      volumes:
        - name: diun-config
          configMap:
            name: diun-config
  volumeClaimTemplates:
    - metadata:
        name: diun-data
        namespace: linole
      spec:
        accessModes: [ "ReadWriteOnce" ]
        storageClassName: "longhorn"
        resources:
          requests:
            storage: 50Mi