image: ghcr.io/openfaas/mqtt-connector:latest
replicas: 1

topic: homeassistant/#
contentType: application/json

broker: tcp://192.168.0.201:1883
clientID: mqttconnector
authPassword: ""

upstream_timeout: 30s # Maximum duration for an invocation
rebuild_interval: 15s
asyncInvoke: false # Invoke via NATS using the function's asynchronous route
basic_auth: true
gateway_url: http://192.168.0.203:8080

nodeSelector: {}
tolerations: []
affinity: {}
