apiVersion: v1
kind: ReplicationController
metadata:
  name: kube-registry-v0
  namespace: kube-system
  labels:
    k8s-app: kube-registry
    version: v0
spec:
  replicas: 1
  selector:
    k8s-app: kube-registry
    version: v0
    kubernetes.io/hostname: linole
  template:
    metadata:
      labels:
        k8s-app: kube-registry
        version: v0
        kubernetes.io/hostname: linole
    spec:
      containers:
        - name: registry
          image: registry:2
          resources:
            limits:
              cpu: 100m
              memory: 200Mi
          env:
            - name: REGISTRY_HTTP_ADDR
              value: :5000
            - name: REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY
              value: /var/lib/k3s/registry
          volumeMounts:
            - name: image-store
              mountPath: /var/lib/k3s/registry
          ports:
            - containerPort: 5000
              name: registry
              protocol: TCP
      volumes:
        - name: image-store
          hostPath:
            path: /var/lib/k3s/registry-storage
          #emptyDir: {}