apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaBridge
metadata:
  name: kafka-bridge
  namespace: kafka
spec:
  replicas: 3
  bootstrapServers: kafka-cluster-kafka-bootstrap:9092
  http:
    port: 8080