apiVersion: v1
kind: Service
metadata:
  name: kube-dns-public
  namespace: kube-system
spec:
  type: LoadBalancer
  ports:
    - port: 53
      protocol: UDP
      name: dns
    - port: 53
      protocol: TCP
      name: dns-tcp
  selector:
    k8s-app: kube-dns