apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: postgres-external
spec:
  ports:
    - port: 5432
      targetPort: 5432
  clusterIP: None
---
apiVersion: v1
kind: Endpoints
metadata:
  name: postgres
  namespace: postgres-external
subsets:
  - addresses:
      - ip: 192.168.10.2
    ports:
      - port: 5432