apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-ui
  namespace: kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-ui
  template:
    metadata:
      labels:
        app: kafka-ui
    spec:
      containers:
        - name: kafka-ui
          image: provectuslabs/kafka-ui:latest 
          ports:
            - containerPort: 8080
          env:
            - name: AUTH_TYPE
              value: "DISABLED"
            - name: KAFKA_CLUSTERS_0_NAME
              value: "kafka"
            - name: KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS
              value: "kafka-kafka-bootstrap.kafka:9091,kafka-kafka-bootstrap.kafka:9092,kafka-kafka-bootstrap.kafka:9093"
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-ui
  namespace: kafka
spec:
  selector:
    app: kafka-ui
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080