apiVersion: apps/v1
kind: Deployment
metadata:
  name: donetick
  namespace: apps
  labels:
    app: donetick
spec:
  replicas: 1
  selector:
    matchLabels:
      app: donetick
  template:
    metadata:
      labels:
        app: donetick
    spec: 
      containers:
        - name: donetick
          image: donetick/donetick:latest
          ports:
            - containerPort: 2021 
          env:
            - name: DT_ENV
              value: "selfhosted" 
            - name: DT_SERVER_CORS_ALLOW_ORIGINS
              value: "tasks.linole.org" 
            - name: DT_DATABASE_TYPE
              value: "postgres" 
          envFrom:
          - secretRef:
              name: donetick-secrets