apiVersion: v1
kind: Service
metadata:
  name: donetick
  namespace: apps
  labels:
    app: donetick
spec:
  type: LoadBalancer
  selector:
    app: donetick
  ports:
    - port: 2021
      targetPort: 2021 
