apiVersion: v1
kind: Service
metadata:
  name: zigbee2mqtt
  namespace: bridges
spec:
  type: LoadBalancer
  selector:
    app: zigbee2mqtt
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080