#############################
# templates below this line #
#############################

 

#############################
# datasets below this line  #
#############################

[ssd/appdata]
        frequently = 0
        hourly = 0
        daily = 7
        weekly = 2
        monthly = 0
        yearly = 0
        autosnap = yes
        autoprune = yes
        recursive           = yes
        script_timeout      = 7200
        post_snapshot_script = /usr/local/sanoid/scripts/post_snapshot.sh
        pruning_script       = /usr/local/sanoid/scripts/pruning_script.sh

[ssd/vm/homeassistant-zvol]
        frequently = 0
        hourly = 0
        daily = 7
        weekly = 2
        monthly = 0
        yearly = 0
        autosnap = yes
        autoprune = yes
        recursive           = no
        script_timeout      = 7200
        post_snapshot_script = /usr/local/sanoid/scripts/post_snapshot.sh
        pruning_script       = /usr/local/sanoid/scripts/pruning_script.sh