apiVersion: v1
kind: Service
metadata:  
  name: kafka-kafka-bootstrap-public
  namespace: kafka 
spec: 
  ports:
    - name: tcp-replication
      port: 9091
      protocol: TCP
      targetPort: 9091
    - name: tcp-clients
      port: 9092
      protocol: TCP
      targetPort: 9092
    - name: tcp-clientstls
      port: 9093
      protocol: TCP
      targetPort: 9093
  selector:
    strimzi.io/broker-role: 'true'
    strimzi.io/cluster: kafka
    strimzi.io/kind: Kafka
    strimzi.io/name: kafka-kafka 
  type: LoadBalancer 
