apiVersion: batch/v1
kind: CronJob
metadata:
  name: nextcloud-cronjob
  labels:
    app: nextcloud
spec:
  schedule: "*/5 * * * *"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          securityContext:
            runAsUser: 1000
          containers:
            - name: nextcloud-cronjob
              image: busybox
              args:
                - /bin/sh
                - -c
                - "wget -q -O - --header 'Host: localhost' http://nextcloud.linole.svc.cluster.local/cron.php"
          restartPolicy: Never