apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: nextcloud
  namespace: linole
  labels:
    app: nextcloud
spec:
  replicas: 1
  serviceName: nextcloud
  selector:
    matchLabels:
      app: nextcloud
  template:
    metadata:
      namespace: linole
      labels:
        app: nextcloud
    spec:
      containers:
#        - name: nginx
#          image: nginx:latest
#          volumeMounts:
#            - name: nextcloud-shared-storage
#              mountPath: /var/www/html
#            - name: nextcloud-nginx-config
#              mountPath: /etc/nginx/nginx.conf
#              subPath: nginx.conf
        - name: nextcloud
          image: nextcloud:24-apache
          env:
#            - name: NEXTCLOUD_ADMIN_USER
#              valueFrom:
#                secretKeyRef:
#                  name: nextcloud-secrets
#                  key: NEXTCLOUD_ADMIN_USER
#            - name: NEXTCLOUD_ADMIN_PASSWORD
#              valueFrom:
#                secretKeyRef:
#                  name: nextcloud-secrets
#                  key: NEXTCLOUD_ADMIN_PASSWORD
#            - name: OBJECTSTORE_S3_HOST
#              valueFrom:
#                secretKeyRef:
#                  name: nextcloud-secrets
#                  key: OBJECTSTORE_S3_HOST
#            - name: OBJECTSTORE_S3_BUCKET
#              valueFrom:
#                secretKeyRef:
#                  name: nextcloud-secrets
#                  key: OBJECTSTORE_S3_BUCKET
#            - name: OBJECTSTORE_S3_KEY
#              valueFrom:
#                secretKeyRef:
#                  name: nextcloud-secrets
#                  key: OBJECTSTORE_S3_KEY
#            - name: OBJECTSTORE_S3_SECRET
#              valueFrom:
#                secretKeyRef:
#                  name: nextcloud-secrets
#                  key: OBJECTSTORE_S3_SECRET
            - name: REDIS_HOST
              valueFrom:
                secretKeyRef:
                  name: nextcloud-secrets
                  key: REDIS_HOST
            - name: REDIS_HOST_PORT
              valueFrom:
                secretKeyRef:
                  name: nextcloud-secrets
                  key: REDIS_HOST_PORT
            - name: REDIS_HOST_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: nextcloud-secrets
                  key: REDIS_HOST_PASSWORD
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: nextcloud-secrets
                  key: POSTGRES_DB
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: nextcloud-secrets
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: nextcloud-secrets
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_HOST
              valueFrom:
                secretKeyRef:
                  name: nextcloud-secrets
                  key: POSTGRES_HOST
            - name: NEXTCLOUD_TRUSTED_DOMAINS
              valueFrom:
                secretKeyRef:
                  name: nextcloud-secrets
                  key: NEXTCLOUD_TRUSTED_DOMAINS
#            - name: OVERWRITECLIURL
#              valueFrom:
#                secretKeyRef:
#                  name: nextcloud-secrets
#                  key: OVERWRITECLIURL
#            - name: OVERWRITEHOST
#              valueFrom:
#                secretKeyRef:
#                  name: nextcloud-secrets
#                  key: OVERWRITEHOST
#            - name: OVERWRITEPROTOCOL
#              valueFrom:
#                secretKeyRef:
#                  name: nextcloud-secrets
#                  key: OVERWRITEPROTOCOL
          volumeMounts:
            - name: nextcloud-persistent-storage
              mountPath: /var/www/html
      volumes:
#        - name: nextcloud-shared-storage
#          emptyDir: { }
        - name: nextcloud-nginx-config
          configMap:
            name: nextcloud-nginx-config
  volumeClaimTemplates:
    - metadata:
        name: nextcloud-persistent-storage
        namespace: linole
      spec:
        accessModes: [ "ReadWriteOnce" ]
        storageClassName: "longhorn"
        resources:
          requests:
            storage: 10Gi