apiVersion: v1
kind: Service
metadata:
  name: postgres-public
  namespace: postgres
  labels:
    app: postgres
spec:
  selector:
    app: postgres
  type: LoadBalancer
  ports:
    - name: postgres-port
      protocol: TCP
      port: 5432
      targetPort: 5432
    - name: pgbackrest
      port: 8081
      targetPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-internal
  namespace: postgres
  labels:
    app: postgres
spec:
  type: NodePort
  ports:
    - name: postgres-port
      protocol: TCP
      port: 5432
      targetPort: 5432
    - name: pgbackrest
      port: 8081
      targetPort: 8081
  selector:
    app: postgres