apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mpd-music-pvc
  namespace: media
spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 4Ti
  volumeName: mpd-music
--- 
# Volumes:
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mpd-music
spec:
  capacity:
    storage: 4Ti
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-path
  local:
    path: /hdd/music
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - master0
 