---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: camera-recorder-data-entranceroof
  namespace: processors
spec:
  capacity:
    storage: 500Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-path
  local:
    path: /surveillance/entrance_roof  # <-- your ZFS mount point
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - master0   
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: camera-recorder-data-entranceroof-pvc
  namespace: processors
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 500Gi
  volumeName: camera-recorder-data-entranceroof