apiVersion: v1
kind: Service
metadata:
  name: bluetooth-api
  namespace: linole
spec:
  type: ClusterIP
  selector:
    app: bluetooth-api
  ports:
    - port: 8000
      targetPort: 8000
      name: http
  loadBalancerIP: 192.168.0.203