services:
  motion-detector:
    build:
      context: .
      dockerfile: Dockerfile
    environment: 
      - LOG_LEVEL=INFO
      - ENTRANCE_ROOF_STREAM_URL=rtsp://192.168.10.208:8554/office_test 
      - KAFKA_BOOTSTRAP_SERVERS=kafka-kafka-bootstrap.kafka:9092
      - TF_CPP_MIN_LOG_LEVEL=0
    network_mode: host
    privileged: true
    volumes:
      - /dev/bus/usb:/dev/bus/usb 
    restart: unless-stopped


 