apiVersion: apps/v1
kind: Deployment
metadata:
  name: amqp-processor
  namespace: processors
  labels:
    app: amqp-processor
    role: processor
spec:
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: amqp-processor
  template:
    metadata:
      labels:
        app: amqp-processor
        role: processor
    spec:
      containers:
        - name: amqp-processor
          image: ghcr.io/ole-klokkhammer/amqp-processor:1.0.12
          imagePullPolicy: IfNotPresent
          env:
            - name: LOG_LEVEL
              value: "info"
            - name: RABBITMQ_HOST
              value: "rabbitmq.brokers"
            - name: RABBITMQ_USER
              value: "guest"
            - name: RABBITMQ_PASSWORD
              value: "guest"
