apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: rabbitmq-secrets
  namespace: brokers
spec:
  refreshInterval: "15s"
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  target:
    name: rabbitmq-secrets
    creationPolicy: Owner
  data:
    - secretKey: RABBITMQ_DEFAULT_USER
      remoteRef:
        key: brokers/rabbitmq/guest
        property: RABBITMQ_USER 
    - secretKey: RABBITMQ_DEFAULT_PASS
      remoteRef:
        key: brokers/rabbitmq/guest
        property: RABBITMQ_PASSWORD 