apiVersion: v1
kind: Service
metadata:
  name: ollama
  namespace: llm-services
spec:
  type: LoadBalancer
  selector:
    app: ollama
  ports:
    - port: 11434
      targetPort: 11434
---
apiVersion: v1
kind: Service
metadata:
  name: ollama-internal
  namespace: llm-services
  labels:
    app: ollama
spec:
  type: NodePort
  ports:
    - port: 11434
      targetPort: 11434
  selector:
    app: ollama