apiVersion: apps/v1
kind: Deployment
metadata:
  name: frame-assembler
  namespace: camera-processors
  labels:
    app: frame-assembler
spec:
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: frame-assembler
  template:
    metadata:
      labels:
        app: frame-assembler
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/hostname
                    operator: In
                    values:
                      - master0
      containers:
        - name: frame-assembler
          image: olklokk/frame-assembler:1.0.0
          env: 
            - name: LOG_LEVEL
              value: "info" 
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: "kafka-kafka-bootstrap.kafka:9092"  