---
# Source: promscale/templates/service-account.yaml
apiVersion: v1
kind: ServiceAccount
automountServiceAccountToken: false
metadata:
  name: promscale
  namespace: default
  labels:
    app: promscale
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: promscale
  namespace: default
  labels:
    app: promscale
spec:
  endpoints:
    - interval: 30s
      port: metrics-port
      path: /metrics
  selector:
    matchLabels:
      app: promscale
---