# Source: promscale/templates/secret-connection.yaml
apiVersion: v1
kind: Secret
metadata:
  name: promscale
  namespace: default
  labels:
    app: promscale
stringData:
  PROMSCALE_DB_PORT: "5432"
  PROMSCALE_DB_HOST: "timescaledb"
  PROMSCALE_DB_NAME: "promscale"
  PROMSCALE_DB_USER: "postgres"
  PROMSCALE_DB_PASSWORD: "xxx"
  PROMSCALE_DB_SSL_MODE: "require"
---