apiVersion: v1
kind: Service
metadata:
  name: broker-mqtt
  namespace: linole
  labels:
    app: broker-mqtt
spec:
  type: LoadBalancer
  ports:
    - port: 1883
      targetPort: 1883
      name: tcp
  selector:
    app: broker-mqtt
  loadBalancerIP: 192.168.0.205