apiVersion: v1
kind: Service
metadata:
  name: mosquitto-external
  namespace: linole
  labels:
    app: mosquitto
spec:
  type: LoadBalancer
  ports:
    - port: 1883
      targetPort: 1883
      name: tcp
  selector:
    app: mosquitto
  loadBalancerIP: 192.168.0.205
---
apiVersion: v1
kind: Service
metadata:
  name: mosquitto-internal
  namespace: linole
  labels:
    app: mosquitto
spec:
  type: NodePort
  ports:
    - port: 1883
      targetPort: 1883
      name: tcp
  selector:
    app: mosquitto