apiVersion: v1
kind: Service
metadata:
  name: kibana-kb-http-public
  namespace: default
  labels:
    common.k8s.elastic.co/type: kibana
    kibana.k8s.elastic.co/name: kibana
spec:
  type: LoadBalancer
  ports:
    - name: https
      protocol: TCP
      port: 5601
      targetPort: 5601
  selector:
    common.k8s.elastic.co/type: kibana
    kibana.k8s.elastic.co/name: kibana
  loadBalancerIP: 192.168.0.208