---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: lightscene-mqtt
  namespace: linole
  labels:
    app: lightscene-mqtt
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lightscene-mqtt
  template:
    metadata:
      labels:
        app: lightscene-mqtt
    spec:
      containers:
        - name: lightscene-mqtt
          image: olklokk/lightscene-mqtt:latest
          env:
            - name: HOST
              value: "broker-mqtt.linole"
