http:
  routers:
    matrix:
      rule: "Host(`matrix.cloud.core.homelan`)"
      entrypoints: [ web ]        # :80 — websecure:443 once you get TLS
      service: matrix
  services:
    matrix:
      loadBalancer:
        servers:
          - url: "http://matrix:8008"