- platform: time_date
  display_options:
    - 'time'
    - 'date'
    - 'date_time'
    - 'date_time_utc'
    - 'date_time_iso'
    - 'time_date'
    - 'time_utc'
    - 'beat'
- platform: moon
- platform: systemmonitor
  resources:
    - type: memory_free
    - type: swap_use_percent
    - type: load_1m
    - type: load_5m
    - type: load_15m
    - type: processor_use
    - type: last_boot
- platform: entur_public_transport
  stop_ids:
    - 'NSR:StopPlace:58403' # https://www.home-assistant.io/integrations/entur_public_transport
    - 'NSR:StopPlace:58381'
    - 'NSR:StopPlace:58263'
    - 'NSR:StopPlace:6035'
    - 'NSR:StopPlace:58194'
  show_on_map: true
  expand_platforms: true
  number_of_departures: 3
  omit_non_boarding: true
- platform: template
  sensors:
    kitchen_temperature:
      friendly_name: "Kitchen Temperature"
      unit_of_measurement: 'degrees'
      value_template: "{{ state_attr('climate.kitchen', 'current_temperature') }}"
    livingroom_hallway_temperature:
      friendly_name: "Livingroom Hallway Temperature"
      unit_of_measurement: 'degrees'
      value_template: "{{ state_attr('climate.millheat2', 'current_temperature') }}"
    livingroom_window_temperature:
      friendly_name: "Livingroom Window Temperature"
      unit_of_measurement: 'degrees'
      value_template: "{{ state_attr('climate.millheat1', 'current_temperature') }}"
    apartment_temperature:
      friendly_name: "Apartment Temperature"
      unit_of_measurement: 'degrees'
      value_template: "{{ 
          ((
            state_attr('climate.millheat2', 'current_temperature') +
            state_attr('climate.kitchen', 'current_temperature') +
            states('sensor.airthings_wave_plus_1_temperature')|int
          ) / 3) | round(1)
      }}"

- platform: mqtt
  state_topic: bluetooth/airthings/co2
  name: "airthings/wave_plus_1/co2"
  unit_of_measurement: "ppm"
  icon: mdi:cloud
- platform: mqtt
  state_topic: bluetooth/airthings/voc
  name: "airthings/wave_plus_1/voc"
  unit_of_measurement: "ppb"
- platform: mqtt
  state_topic: bluetooth/airthings/humidity
  name: "airthings/wave_plus_1/humidity"
  unit_of_measurement: "%"
  device_class: humidity
- platform: mqtt
  state_topic: bluetooth/airthings/radon_st_avg
  name: "airthings/wave_plus_1/radon_short"
  unit_of_measurement: "Bq/m3"
  icon: mdi:cloud
- platform: mqtt
  state_topic: bluetooth/airthings/radon_lt_avg
  name: "airthings/wave_plus_1/radon_long"
  unit_of_measurement: "Bq/m3"
  icon: mdi:cloud
- platform: mqtt
  state_topic: bluetooth/airthings/pressure
  name: "airthings/wave_plus_1/pressure"
  unit_of_measurement: "mbar"
  device_class: pressure
  icon: mdi:gauge
- platform: mqtt
  state_topic: bluetooth/airthings/temperature
  name: "airthings/wave_plus_1/temperature"
  unit_of_measurement: "°C"
  device_class: temperature

- platform: mqtt
  state_topic: bluetooth/miflora/plant_sensor/temperature
  name: "miflora/plant_sensor_1/temperature"
  unit_of_measurement: "°C"
- platform: mqtt
  state_topic: bluetooth/miflora/plant_sensor/moisture
  name: "miflora/plant_sensor_1/moisture"
  unit_of_measurement: "%"
- platform: mqtt
  state_topic: bluetooth/miflora/plant_sensor/light
  name: "miflora/plant_sensor_1/light"
  unit_of_measurement: "lux"
- platform: mqtt
  state_topic: bluetooth/miflora/plant_sensor/conductivity
  name: "miflora/plant_sensor_1/conductivity"
  unit_of_measurement: "us/cm"
- platform: mqtt
  state_topic: bluetooth/miflora/plant_sensor/battery
  name: "miflora/plant_sensor_1/battery"
  unit_of_measurement: "%"

- platform: mqtt
  state_topic: bluetooth/paxcalima/bathroom_fan/humidity
  name: "paxcalima/bathroom_fan/humidity"
  unit_of_measurement: "%"
  device_class: humidity
- platform: mqtt
  state_topic: bluetooth/paxcalima/bathroom_fan/temperature
  name: "paxcalima/bathroom_fan/temperature"
  unit_of_measurement: "°C"
- platform: mqtt
  state_topic: bluetooth/paxcalima/bathroom_fan/fan_speed
  name: "paxcalima/bathroom_fan/fan_speed"
  unit_of_measurement: "rpm"
- platform: mqtt
  state_topic: bluetooth/paxcalima/bathroom_fan/mode
  name: "paxcalima/bathroom_fan/mode"

- platform: mqtt
  state_topic: bluetooth/oralb/ole/presence
  name: "oralb/ole/presence"

- platform: mqtt
  state_topic: dyson/J9S-EU-PHA4334A/hact
  name: "dyson/humidify_cool/humidity"
  unit_of_measurement: "%"
  device_class: humidity
- platform: mqtt
  state_topic: dyson/J9S-EU-PHA4334A/tact
  name: "dyson/humidify_cool/temperature"
  unit_of_measurement: "°C"
  device_class: temperature
- platform: mqtt
  state_topic: dyson/J9S-EU-PHA4334A/pm25
  name: "dyson/humidify_cool/pm2.5"
  unit_of_measurement: "ug/m3"
- platform: mqtt
  state_topic: dyson/J9S-EU-PHA4334A/pm10
  name: "dyson/humidify_cool/pm10"
  unit_of_measurement: "ug/m3"
- platform: mqtt
  state_topic: dyson/J9S-EU-PHA4334A/va10
  name: "dyson/humidify_cool/voc"
  unit_of_measurement: "d"
- platform: mqtt
  state_topic: dyson/J9S-EU-PHA4334A/noxl
  name: "dyson/humidify_cool/nox"
  unit_of_measurement: "d"

- platform: mqtt
  state_topic: dyson/A1B-EU-NKA0949A/hact
  name: "dyson/hot_cool/humidity"
  unit_of_measurement: "%"
  device_class: humidity
- platform: mqtt
  state_topic: dyson/A1B-EU-NKA0949A/tact
  name: "dyson/hot_cool/temperature"
  unit_of_measurement: "°C"
  device_class: temperature
- platform: mqtt
  state_topic: dyson/A1B-EU-NKA0949A/sltm
  name: "dyson/hot_cool/sltm"
- platform: mqtt
  state_topic: dyson/A1B-EU-NKA0949A/va10
  name: "dyson/hot_cool/voc"
  unit_of_measurement: "d"
- platform: mqtt
  state_topic: dyson/A1B-EU-NKA0949A/pm10
  name: "dyson/hot_cool/pm10"
  unit_of_measurement: "ug/m3"
- platform: mqtt
  state_topic: dyson/A1B-EU-NKA0949A/pm25
  name: "dyson/hot_cool/pm2.5"
  unit_of_measurement: "ug/m3"
- platform: mqtt
  state_topic: dyson/A1B-EU-NKA0949A/p10r
  name: "dyson/hot_cool/p10r"
- platform: mqtt
  state_topic: dyson/A1B-EU-NKA0949A/p25r
  name: "dyson/hot_cool/p25r"
- platform: mqtt
  state_topic: dyson/A1B-EU-NKA0949A/noxl
  name: "dyson/hot_cool/nox"
  unit_of_measurement: "d"
- platform: mqtt
  state_topic: dyson/A1B-EU-NKA0949A/hchr
  name: "dyson/hot_cool/hchr"
- platform: mqtt
  state_topic: dyson/A1B-EU-NKA0949A/hcho
  name: "dyson/hot_cool/hcho"