custom_header:
  disabled_mode: true

title: 'Home Assistant'
views: 
  - path: home_mobile
    icon: 'hass:home-assistant'
    title: Home
    badges:
      - entity: person.ole
      - entity: person.linn
      - entity: sensor.airthings_humidity
      - entity: sensor.airthings_short_term_radon
      - entity: sensor.airthings_co2
      - entity: sensor.airthings_temperature
      - entity: sensor.airthings_pressure
      - entity: sensor.airthings_voc
    cards:
      - type: entities
        title: Light
        entities:
          - light.kitchen
          - light.bedroom
          - light.entrance
          - light.garden
      - type: weather-forecast
        entity: weather.home
      - type: button
        tap_action:
          action: toggle
        show_icon: true
        entity: switch.d_link_smart_plug_w215
        name: Garden hose 
      - type: sensor
        entity: sensor.moon
      - type: entities
        entities:
          - entity: sun.sun
      - type: light
        entity: light.bedroom
      - type: light
        entity: light.entrance
      - type: light
        entity: light.kitchen
      - type: custom:flower-card
        entity: plant.miflora1
        species: "blue_pitts"
  - path: heaters
    icon: 'mdi:fireplace'
    title: Heaters
    badges: []
    cards:
      - type: sensor
        entity: sensor.apartment_temperature
        graph: line
        detail: 2
      - type: vertical-stack
        title: Livingroom Left
        cards:
          - type: thermostat
            entity: climate.millheat1
          - type: history-graph
            entities:
              - entity: climate.millheat1
            hours_to_show: 24
            refresh_interval: 30
      - type: vertical-stack
        title: Livingroom Right
        cards:
          - type: thermostat
            entity: climate.millheat2
          - type: history-graph
            entities:
              - entity: climate.millheat2
            hours_to_show: 24
            refresh_interval: 30
      - type: vertical-stack
        title: Kitchen
        cards:
          - type: thermostat
            entity: climate.kitchen
          - type: history-graph
            entities:
              - entity: climate.kitchen
            hours_to_show: 24
            refresh_interval: 30
  - path: airthings
    icon: 'mdi:periodic-table-co2'
    title: Airthings
    badges: []
    cards:
      - type: history-graph
        title: Inside
        entities:
          - entity: sensor.airthings_wave_plus_1_co2
          - entity: sensor.airthings_wave_plus_1_voc
          - entity: sensor.airthings_wave_plus_1_short_term_radon
          - entity: sensor.airthings_wave_plus_1_pressure
          - entity: sensor.airthings_wave_plus_1_temperature
          - entity: sensor.airthings_wave_plus_1_humidity
        hours_to_show: 48
        refresh_interval: 30
      - type: history-graph
        title: Outside
        entities:
          - entity: sensor.current_ozone_level
          - entity: sensor.current_uv_index
          - entity: sensor.current_uv_level
          - entity: sensor.max_uv_index
          - entity: sensor.skin_type_1_safe_exposure_time
          - entity: sensor.skin_type_2_safe_exposure_time
          - entity: sensor.skin_type_3_safe_exposure_time
          - entity: sensor.skin_type_4_safe_exposure_time
          - entity: sensor.skin_type_5_safe_exposure_time
          - entity: sensor.skin_type_6_safe_exposure_time
        hours_to_show: 48
        refresh_interval: 30
  - path: media
    icon: 'mdi:record-player'
    title: Media
    badges: []
    cards:
      - type: media-control
        entity: media_player.living_room_tv
      - type: media-control
        entity: media_player.spotify_ole_klokkhammer
      - type: media-control
        entity: media_player.dlna_digital_media_renderer
  - path: system
    icon: 'mdi:server-network'
    title: System
    badges: []
    cards:
      - type: entities
        entities:
          - entity: sensor.cert_expiry_linole_duckdns_org_6102
      - type: sensor
        entity: sensor.last_boot
      - type: history-graph
        title: Linole Server
        entities:
          - entity: sensor.memory_free
          - entity: sensor.disk_use_percent_run_media_ole_data
          - entity: sensor.load_1m
          - entity: sensor.processor_use
          - entity: sensor.swap_use_percent
          - entity: sensor.load_5m
          - entity: sensor.load_15m
        hours_to_show: 48
        refresh_interval: 30
      - type: history-graph
        title: PiHole
        entities:
          - entity: sensor.pi_hole_ads_blocked_today
          - entity: sensor.pi_hole_ads_percentage_blocked_today
          - entity: sensor.pi_hole_dns_queries_cached
          - entity: sensor.pi_hole_dns_queries_forwarded
          - entity: sensor.pi_hole_dns_queries_today
          - entity: sensor.pi_hole_dns_unique_clients
          - entity: sensor.pi_hole_dns_unique_domains
          - entity: sensor.pi_hole_domains_blocked
          - entity: sensor.pi_hole_seen_clients
        hours_to_show: 48
        refresh_interval: 30