apiVersion: apps/v1
kind: Deployment
metadata:
  name: bluetooth-parser
  namespace: processors
  labels:
    app: bluetooth-parser
    role: processor
spec:
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: bluetooth-parser
  template:
    metadata:
      labels:
        app: bluetooth-parser
        role: processor
    spec:
      containers:
        - name: bluetooth-parser
          image: ghcr.io/ole-klokkhammer/bluetooth-parser:1.0.1
          imagePullPolicy: IfNotPresent
          env:
            - name: LOG_LEVEL
              value: "info"
            - name: RABBITMQ_HOST
              value: "rabbitmq.brokers"
            - name: RABBITMQ_USER
              value: "guest"
            - name: RABBITMQ_PASSWORD
              value: "guest"
