#!/usr/bin/env bash
#
# agent.sh — register a Prime Agent workbench service per workspace.
#
# Model B (one service per workspace, keep-alive + manual start):
#
#   agent.sh <workspace-path>              register + start  prime-agent-<slug>
#   agent.sh <workspace-path> <slug>       register with an explicit service suffix
#   agent.sh remove  <slug>                stop + unregister + drop its state volume
#   agent.sh list                          show every registered workspace
#   agent.sh exec|shell|status|logs|ps|start|stop  <slug>
#
# Behaviour:
#   * For each workspace a unique quadlet is written to
#         ~/.config/containers/systemd/prime-agent-<slug>.container
#     which the user-level systemd quadlet generator turns into the
#     first-class unit  prime-agent-<slug>.service.
#   * The main process is a keep-alive (`Exec=sleep infinity`). Start the
#     interactive TUI on demand:  agent.sh exec <slug>
#   * Each workspace gets its own named state volume (prime-agent-<slug>-state),
#     so N workspaces can run side by side without clobbering each other's
#     sessions / kernel venv.
#
# Prereqs: `make image` (builds prime-agent:latest) and `loginctl enable-linger $USER`.

set -euo pipefail

IMAGE="prime-agent:latest"
SYSDDIR="${HOME}/.config/containers/systemd"
APPLIANCE_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
MODEL_JSON="${APPLIANCE_DIR}/podman/models.json"

die() { echo "agent.sh: error: $*" >&2; exit 1; }
slunit() { echo "prime-agent-$1"; }

# slug: lowercase, non-alnum -> '-', squeeze runs, trim edge dashes.
sanitize() {
    echo "$1" | tr '[:upper:]' '[:lower:]' | sed -E 's/[^a-z0-9]+/-/g; s/^-+//; s/-+$//'
}

require_image() {
    if ! podman image exists "${IMAGE}" >/dev/null 2>&1; then
        echo "agent.sh: image ${IMAGE} not present."
        echo "        build it first:  cd ${APPLIANCE_DIR}/podman && make image"
        exit 1
    fi
}

register() {
    local ws="${1:?usage: agent.sh <workspace-path> [slug]}"
    local slug="${2:-$(sanitize "$(basename "$(realpath "$ws")")")}"
    local unit

    ws="$(realpath "$ws")"
    [[ -d "$ws" ]] || die "workspace is not a directory: ${ws}"
    [[ -n "$slug" ]] || die "could not derive a service slug from ${ws}"
    [[ -f "$MODEL_JSON" ]] || die "models.json not found at ${MODEL_JSON}"
    require_image

    unit="$(slunit "$slug")"
    mkdir -p "$SYSDDIR"

    cat > "${SYSDDIR}/${unit}.container" <<EOF
# ${unit} - Prime Agent workbench for ${ws}
# Generated by agent.sh. Do not edit by hand; \`agent.sh remove ${slug}\` unregisters it.
[Unit]
Description=Prime Agent workbench for ${ws}
After=network-online.target
Wants=network-online.target

[Container]
HostName=${unit}
ContainerName=${unit}
Image=${IMAGE}
Network=host
WorkingDir=/workspace

# Attach this workspace read-write.
Volume=${ws}:/workspace:rw

# Per-workspace persistent state (sessions, auth.json, kernel venv).
Volume=${unit}-state:/home/agent/.prime/agent
Environment=PRIME_AGENT_CODING_AGENT_DIR=/home/agent/.prime/agent

# LLM provider config - the repo copy is the source of truth (read-only).
Volume=${MODEL_JSON}:/home/agent/.prime/agent/models.json:ro

Environment=LOCAL_LLM_KEY=dummy
Environment=TZ=Europe/Oslo

# Keep-alive; drive the TUI with: agent.sh exec ${slug}
Exec=sleep infinity

[Service]
Restart=on-failure
TimeoutStopSec=30
StandardOutput=journal
StandardError=journal

[Install]
WantedBy=default.target
EOF

    systemctl --user daemon-reload
    if systemctl --user is-enabled "${unit}" >/dev/null 2>&1; then
        systemctl --user restart "${unit}"
    else
        systemctl --user enable --now "${unit}" 2>/dev/null || systemctl --user start "${unit}"
    fi

    systemctl --user is-active "${unit}" >/dev/null 2>&1 \
        || echo "agent.sh: ${unit} started but not reporting active yet (checking: systemctl --user status ${unit})"
    echo "registered ${unit} -> ${ws}"
    echo "  state volume : ${unit}-state"
    echo "  start TUI    : agent.sh exec ${slug}"
    echo "  state file   : ${SYSDDIR}/${unit}.container"
}

remove() {
    local slug="${1:?usage: agent.sh remove <slug>}"
    local unit
    unit="$(slunit "$slug")"
    systemctl --user stop "${unit}" 2>/dev/null || true
    rm -f "${SYSDDIR}/${unit}.container"
    systemctl --user daemon-reload 2>/dev/null || true
    podman volume rm "${unit}-state" 2>/dev/null || true
    echo "removed ${unit}"
}

list() {
    local f base ws state
    local found=0
    for f in "${SYSDDIR}"/prime-agent-*.container; do
        [[ -e "$f" ]] || continue
        base="$(basename "$f" .container)"
        ws="$(grep -Em1 ':/workspace' "$f" | sed -E 's|^Volume=(.*):/workspace.*|\1|')"
        state="$(systemctl --user is-active "$base" 2>/dev/null || true)"
        [[ -z "$state" ]] && state="inactive"
        found=1
        printf '%-32s %-10s %s\n' "$base" "$state" "$ws"
    done
    [[ "$found" -eq 1 ]] || echo "(no workspaces registered)"
}

# ---- dispatch -------------------------------------------------------------
cmd="${1:-list}"
case "$cmd" in
    remove|list|exec|shell|status|logs|ps|start|stop) shift ;;
    -*|help|-h)
        grep -E '^#( |$)' "$0" | sed -n '1,40p'; exit 0 ;;
esac

case "$cmd" in
    list) list ;;
    remove) remove "${1:?slug}" ;;
    exec|shell)
        local_slug="${1:?slug}"; unit="$(slunit "$local_slug")"
        case "$cmd" in
            exec)  podman exec -it "$unit" prime-agent ;;
            shell) podman exec -it "$unit" sh ;;
        esac ;;
    status) unit="$(slunit "${1:?slug}")"; systemctl --user status "$unit" ;;
    start)  unit="$(slunit "${1:?slug}")"; systemctl --user start "$unit" ;;
    stop)   unit="$(slunit "${1:?slug}")"; systemctl --user stop "$unit" ;;
    logs)
        unit="$(slunit "${1:?slug}")"
        journalctl --user -u "$unit" -n 40 --no-pager
        echo "--- following (Ctrl-C to stop) ---"
        journalctl --user -u "$unit" -f ;;
    ps) podman ps -a --filter "name=prime-agent-${1:?slug}" ;;
    *) # first arg is a workspace path -> register. No shift here, so keep
       # the original positionals: $1 = workspace, $2 = optional slug.
       register "$1" "${2:-}" ;;
esac
