---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-data
  namespace: postgres
  labels:
    app: postgres
spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 50Gi
  local:
    path: /var/lib/postgresql/data
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - master0
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-config
  namespace: postgres
  labels:
    app: postgres
spec:
  storageClassName: longhorn-single-replica
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 500Mi
  volumeMode: Filesystem
  csi:
    driver: driver.longhorn.io
    fsType: ext4
    volumeHandle: postgres-config
    volumeAttributes:
      numberOfReplicas: "1"