---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: immich-data
  namespace: immich
  labels:
    app: immich
spec:
  storageClassName: local-path
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - master0 
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 500Gi
  local:
    path: /mnt/data