apiVersion: apps/v1
kind: Deployment
metadata:
  name: log-parser
  namespace: event-processors
  labels:
    app: log-parser
spec: 
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: log-parser
  template:
    metadata:
      labels:
        app: log-parser
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/hostname
                    operator: In
                    values:
                      - master0
      containers:
        - name: log-parser
          image: olklokk/log-parser:1.0.31
          env:
            - name: LOG_LEVEL
              value: "info"
              