# https://docs.frigate.video/configuration/
apiVersion: v1
kind: ConfigMap
metadata:
  name: frigate
  namespace: linole
data:
  config.yml: | 
    mqtt: 
      host: "mosquitto-internal.linole"
      port: 1883

    detect:
      fps: 5
    
    birdseye:
      enabled: True
      mode: continuous
      restream: False
      width: 1920
      height: 1080
      quality: 4
    
    detectors:
      coral:
        type: edgetpu
        device: usb
    
    ffmpeg:
      hwaccel_args: preset-nvidia-h264
    
    go2rtc:
      streams:
        entrance_roof:
          - ffmpeg:http://192.168.10.154/flv?port=1935&app=bcs&stream=channel0_main.bcs&user={FRIGATE_REOLINK_USER}&password={FRIGATE_REOLINK_PASSWORD}
        
    cameras:
      # https://docs.frigate.video/configuration/camera_specific/
      entrance_roof:
        ffmpeg:
          inputs:
            - path: rtsp://127.0.0.1:8554/entrance_roof
              roles:
                - record            
            - path: rtsp://127.0.0.1:8554/entrance_roof
              roles:
                - detect
    
    record:
      enabled: True
      retain:
        days: 3
        mode: motion
      events:
        retain:
          default: 30
          mode: motion