# https://github.com/AlexxIT/go2rtc?tab=readme-ov-file#source-ffmpeg
# https://shotstack.io/learn/ffmpeg-blur-video/
# https://docs.frigate.video/configuration/
# https://docs.frigate.video/configuration/reference

logger:
  # Optional: default log level (default: shown below)
  default: info
  # Optional: module by module log level configuration
  logs:
    frigate.mqtt: error
    frigate.event: debug
    ffmpeg: debug

mqtt:
  host: mosquitto-internal.linole
  port: 1883

detect:
  fps: 5

birdseye:
  enabled: true
  mode: continuous
  restream: false
  width: 1920
  height: 1080
  quality: 4

detectors:
  coral:
    type: edgetpu
    device: usb

ffmpeg:
  hwaccel_args: preset-nvidia-h264
  global_args: -loglevel info -hide_banner

# https://stackoverflow.com/questions/53518589/how-to-use-filtering-and-stream-copy-together-with-ffmpeg#53526514
go2rtc:
  streams:
    entrance_roof: |
      ffmpeg:http://192.168.10.154/flv?port=1935&app=bcs&stream=channel0_main.bcs&user={FRIGATE_REOLINK_USER}&password={FRIGATE_REOLINK_PASSWORD}#video=h264#audio=opus#raw=-filter_complex "[0:v]crop=450:350:1470:700,boxblur=10[mask];[0:v][mask]overlay=1470:700[v]" -map "[v]"

cameras:
  # https://docs.frigate.video/configuration/camera_specific/
  entrance_roof:
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/entrance_roof
          input_args: preset-rtsp-restream
          roles:
            - detect
            - record
            - audio

record:
  enabled: true
  retain:
    days: 3
    mode: motion
  events:
    retain:
      default: 30
      mode: motion
version: 0.14
