apiVersion: v1
kind: ConfigMap
metadata:
  name: rabbitmq-config
  namespace: brokers
data:
  rabbitmq.conf: |
    # Your RabbitMQ configuration goes here
    mqtt.allow_anonymous = true
    mqtt.listeners.ssl = none  
    mqtt.vhost = /
    mqtt.exchange = amq.topic
    mqtt.retained_message_store = rabbit_mqtt_retained_msg_store_dets

    management.oauth_enabled = true
    management.oauth_client_id = rabbitmq

    management.oauth_scopes = openid profile rabbitmq.tag:management
    management.oauth_provider_url = https://auth.linole.org/realms/master
    management.oauth_disable_basic_auth = false

    auth_oauth2.verify_aud = true
    auth_oauth2.resource_server_id = rabbitmq
    auth_oauth2.preferred_username_claims.1 = preferred_username
    auth_oauth2.issuer = https://auth.linole.org/realms/master
    auth_oauth2.jwks_url  = https://auth.linole.org/realms/master/protocol/openid-connect/certs

    auth_oauth2.additional_scopes_key = roles realm_access.roles resource_access.rabbitmq.roles