apiVersion: v1
kind: PersistentVolume
metadata:
  name: diun-data
  namespace: linole
spec:
  capacity:
    storage: 50Mi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  csi:
    driver: driver.longhorn.io
    fsType: ext4
    volumeAttributes:
      numberOfReplicas: "1"
    volumeHandle: diun-data
  storageClassName: longhorn-single-replica