apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: torrent-stack
  namespace: apps
  labels:
    app: torrent-stack
spec:
  serviceName: torrent-stack
  replicas: 1
  selector:
    matchLabels:
      app: torrent-stack
  template:
    metadata:
      labels:
        app: torrent-stack
    spec:
      restartPolicy: Always
      initContainers:
        - name: check-torrent-config-mount # CHECK ZFS MOUNT
          image: busybox
          command:
            [
              "sh",
              "-c",
              'test -f /fs/.mounted || (echo "File mount missing" && exit 1)',
            ]
          volumeMounts:
            - mountPath: /fs
              name: torrent-config
        - name: apply-sysctl # DISABLE IPV6
          image: busybox
          command: ["sh", "-c", "sysctl -p /etc/sysctl.conf || true"]
          securityContext:
            privileged: true
          volumeMounts:
            - name: torrent-config
              subPath: nordvpn/etc/sysctl.conf
              mountPath: /etc/sysctl.conf 
        - name: set-ulimit # Set proper ulimits
          image: busybox
          command: ["sh", "-c", "ulimit -n 65536"]
      containers:
        - name: vpn
          image: ghcr.io/bubuntux/nordlynx
          securityContext:
            capabilities:
              add: ["NET_ADMIN", "NET_RAW"]
          volumeMounts:
            - name: lib-modules
              mountPath: /lib/modules
              readOnly: true 
          # sysctls and other advanced options may require privileged DaemonSet or host networking
          env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: TZ
              value: "Europe/Oslo"
            - name: CONNECT
              value: "Norway"
            - name: TECHNOLOGY
              value: "OpenVPN" # "NordLynx" | "OpenVPN"
            - name: PROTOCOL
              value: "UDP"
            - name: KILLSWITCH
              value: "on"
            - name: USER
              valueFrom:
                secretKeyRef:
                  name: torrent-secrets
                  key: USER
            - name: TOKEN
              valueFrom:
                secretKeyRef:
                  name: torrent-secrets
                  key: TOKEN
            - name: PRIVATE_KEY
              valueFrom:
                secretKeyRef:
                  name: torrent-secrets
                  key: PRIVATE_KEY

        - name: qbittorrent
          image: ghcr.io/linuxserver/qbittorrent
          ports:
            - containerPort: 6881
              protocol: TCP
            - containerPort: 6881
              protocol: UDP
            - containerPort: 8080 
          volumeMounts:
            - name: torrent-data
              subPath: downloads
              mountPath: /downloads
            - name: torrent-config
              subPath: qbittorrent
              mountPath: /config
          env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
          # Shares network with vpn container

        - name: radarr
          image: ghcr.io/linuxserver/radarr
          ports:
            - containerPort: 7878
          volumeMounts:
            - name: torrent-config
              subPath: radarr
              mountPath: /config
            - name: torrent-data
              subPath: movies
              mountPath: /movies
            - name: torrent-data
              subPath: downloads
              mountPath: /downloads
          env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
          # Shares network with vpn container

        - name: sonarr
          image: ghcr.io/linuxserver/sonarr
          ports:
            - containerPort: 8989
          volumeMounts:
            - name: torrent-config
              subPath: sonarr
              mountPath: /config
            - name: torrent-data
              subPath: tv
              mountPath: /tv
            - name: torrent-data
              subPath: downloads
              mountPath: /downloads
          env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
          # Shares network with vpn container

        - name: lidarr
          image: ghcr.io/linuxserver/lidarr
          ports:
            - containerPort: 8686
          volumeMounts:
            - name: torrent-config
              subPath: lidarr
              mountPath: /config
            - name: torrent-data
              subPath: music
              mountPath: /music
            - name: torrent-data
              subPath: downloads
              mountPath: /downloads
          env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
          # Shares network with vpn container

        - name: jackett
          image: ghcr.io/linuxserver/jackett
          ports:
            - containerPort: 9117
          volumeMounts:
            - name: torrent-config
              subPath: jackett
              mountPath: /config
            - name: torrent-data
              subPath: downloads
              mountPath: /downloads
          env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
          # Shares network with vpn container

        - name: jellyseerr
          image: fallenbagel/jellyseerr:latest
          ports:
            - containerPort: 5055
          volumeMounts:
            - name: torrent-config
              subPath: jellyseerr
              mountPath: /app/config
          env:
            - name: LOG_LEVEL
              value: "info"
            - name: TZ
              value: "Europe/Oslo"
            - name: PORT
              value: "5055"
          # Shares network with vpn container

      volumes:
        - name: torrent-data
          hostPath:
            path: /mnt/big/media
        - name: torrent-config
          persistentVolumeClaim:
            claimName: torrent-config-pvc
        - name: lib-modules
          hostPath:
            path: /lib/modules
