apiVersion: apps/v1
kind: Deployment
metadata:
  name: scheduler-fn
  namespace: functions
  labels:
    app: scheduler-fn
spec:
  replicas: 1
  selector:
    matchLabels:
      app: scheduler-fn
  template:
    metadata:
      labels:
        app: scheduler-fn
    spec:
      containers:
        - name: scheduler
          image: olklokk/scheduler:latest
          env:
            - name: HOST
              value: "mosquitto-internal.linole"