apiVersion: v1
kind: PersistentVolume
metadata:
  name: homeassistant-data
  namespace: linole
  labels:
    app: homeassistant
spec:
  capacity:
    storage: 500Mi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  csi:
    driver: driver.longhorn.io
    fsType: ext4
    volumeAttributes:
      numberOfReplicas: "1"
    volumeHandle: homeassistant-data
  storageClassName: longhorn-single-replica