apiVersion: pingcap.com/v1alpha1
kind: TidbMonitor
metadata:
  name: tidb-arm64
spec:
  replicas: 1
  clusters:
    - name: tidb-arm64
  prometheus:
    baseImage: prom/prometheus
    version: v2.27.1
  grafana:
    baseImage: grafana/grafana
    version: 7.5.11
  initializer:
    baseImage: pingcap/tidb-monitor-initializer-arm64
    version: v5.4.0
  reloader:
    baseImage: pingcap/tidb-monitor-reloader-arm64
    version: v1.0.1
  imagePullPolicy: IfNotPresent
