
# Source: promscale/templates/svc-promscale.yaml
apiVersion: v1
kind: Service
metadata:
  name: promscale-connector
  namespace: default
  labels:
    app: promscale
spec:
  selector:
    app: promscale
  type: ClusterIP
  ports:
    - name: metrics-port
      port: 9201
      targetPort: 9201
      protocol: TCP
    - name: otel-port
      port: 9202
      targetPort: 9202
      protocol: TCP
