
# https://github.com/rook/rook/blob/release-1.17/deploy/charts/rook-ceph-cluster/values.yaml
# placement:
#   all:
#     nodeAffinity:
#       required:
#         nodeSelectorTerms:
#           - matchExpressions:
#               - key: kubernetes.io/hostname
#                 operator: In
#                 values:
#                   - master0

cephClusterSpec:
  external:
    enable: true
  cephVersion:
    image: quay.io/ceph/ceph:v19.2.2
  dataDirHostPath: /var/lib/rook
  crashCollector:
    disable: true
  healthCheck:
    daemonHealth:
      mon:
        disabled: false
        interval: 45s
