apiVersion: v1
kind: Service
metadata:
  name: sftpgo
  namespace: apis
spec:
  type: LoadBalancer
  selector:
    app: sftpgo
  ports:
    - name: web
      protocol: TCP
      port: 8080
    - name: ftp
      protocol: TCP
      port: 2121
    - name: sftp
      protocol: TCP
      port: 2022