---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: zigbee2mqtt-data
  namespace: bridges
spec:
  capacity:
    storage: 500Mi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-path
  local:
    path: /k3s/zigbee2mqtt-data  # <-- your ZFS mount point
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - master0   
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: zigbee2mqtt-data-pvc
  namespace: bridges
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 500Mi
  volumeName: zigbee2mqtt-data