apiVersion: v1
kind: PersistentVolume
metadata:
  name: llama-data
  namespace: apis
  labels:
    app: llama-api
spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 15Gi
  local:
    path: /k3s-temp/llama
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - master0
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: llama-data-pvc
  namespace: apis
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 15Gi
  volumeName: llama-data