apiVersion: v1
kind: PersistentVolume
metadata:
  name: redis-data
  namespace: brokers
  labels:
    app: redis
spec:
  storageClassName: local-path
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - master0
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 500Mi
  local:
    path: /k3s-temp/redis
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-data-pvc
  namespace: brokers
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 500Mi
  volumeName: redis-data