---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: ollama-data
  namespace: ollama
  labels:
    app: ollama
spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 50Gi
  local:
    path: /var/lib/ollama
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - master0
