apiVersion: v1
kind: Service
metadata:
  name: owncloud-public
  namespace: linole
  labels:
    app.kubernetes.io/instance: ocis
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: ocis
  annotations:
    meta.helm.sh/release-name: ocis
    meta.helm.sh/release-namespace: linole
spec:
  type: LoadBalancer
  ports:
    - name: http
      protocol: TCP
      port: 9200
      targetPort: 9200
  selector:
    app: proxy
  loadBalancerIP: 192.168.0.209