apiVersion: apps/v1
kind: Deployment
metadata:
  name: kerberos-agent-hallway
  namespace: kerberos
  labels:
    name: kerberos-agent-hallway
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: kerberos-agent-hallway
  template:
    metadata:
      labels:
        app: kerberos-agent-hallway
    spec:
      containers:
        - name: kerberos-agent-hallway
          image: kerberos/agent:latest
          ports:
            - containerPort: 80
              protocol: TCP
          env:
            - name: AGENT_NAME
              value: hallway-camera
            - name: AGENT_TIMEZONE
              value: "Europe/Brussels"
            - name: AGENT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: kerberos-secrets
                  key: AGENT_USERNAME
            - name: AGENT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: kerberos-secrets
                  key: AGENT_PASSWORD
            - name: AGENT_CAPTURE_IPCAMERA_RTSP
              valueFrom:
                secretKeyRef:
                  name: kerberos-secrets
                  key: HALLWAY_RTSP_URL
            - name: AGENT_CAPTURE_IPCAMERA_SUB_RTSP
              valueFrom:
                secretKeyRef:
                  name: kerberos-secrets
                  key: HALLWAY_SUB_RTSP_URL
            # find full list of environment variables here: https://github.com/kerberos-io/agent#override-with-environment-variables