apiVersion: v1
kind: Service
metadata:
  name: kerberos-agent-hallway-svc
  namespace: kerberos
  labels:
    name: kerberos-agent-hallway-svc
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: kerberos-agent-hallway