apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
  namespace: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
        name: postgres
    spec: 
      containers:
        - name: postgres
          image: timescale/timescaledb-ha:pg17
          imagePullPolicy: Always
          ports:
            - name: postgres
              containerPort: 5432
          volumeMounts:
            - name: postgres-pgsocket # use this with sidecar
              mountPath: /var/run/postgresql
            - name: postgres-data
              mountPath: /home/postgres/pgdata/data
            - name: postgres-config
              subPath: pgbackrest.conf
              mountPath: /home/postgres/pgdata/backup/pgbackrest.conf
            - name: postgres-config
              subPath: postgresql.conf
              mountPath: /home/postgres/pgdata/data/postgresql.conf
            # vchord-0.3.0 extension 
            - name: postgres-config
              subPath: extensions/pg17/vchord-0.3.0/pkglibdir/vchord.so
              mountPath: /usr/lib/postgresql/17/lib/vchord.so
            - name: postgres-config
              subPath: extensions/pg17/vchord-0.3.0/sharedir/extension/vchord--0.1.0--0.2.0.sql
              mountPath: /usr/share/postgresql/17/extension/vchord--0.1.0--0.2.0.sql
            - name: postgres-config
              subPath: extensions/pg17/vchord-0.3.0/sharedir/extension/vchord--0.2.0--0.2.1.sql
              mountPath: /usr/share/postgresql/17/extension/vchord--0.2.0--0.2.1.sql
            - name: postgres-config
              subPath: extensions/pg17/vchord-0.3.0/sharedir/extension/vchord--0.2.1--0.2.2.sql
              mountPath: /usr/share/postgresql/17/extension/vchord--0.2.1--0.2.2.sql
            - name: postgres-config
              subPath: extensions/pg17/vchord-0.3.0/sharedir/extension/vchord--0.2.2--0.3.0.sql
              mountPath: /usr/share/postgresql/17/extension/vchord--0.2.2--0.3.0.sql 
            - name: postgres-config
              subPath: extensions/pg17/vchord-0.3.0/sharedir/extension/vchord--0.3.0.sql
              mountPath: /usr/share/postgresql/17/extension/vchord--0.3.0.sql
            - name: postgres-config
              subPath: extensions/pg17/vchord-0.3.0/sharedir/extension/vchord.control
              mountPath: /usr/share/postgresql/17/extension/vchord.control
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-secrets
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secrets
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_HOST_AUTH_METHOD
              valueFrom:
                secretKeyRef:
                  name: postgres-secrets
                  key: POSTGRES_HOST_AUTH_METHOD
        - name: pgbackrest-sidecar
          image: timescale/timescaledb-ha:pg17
          command: ["/bin/sh", "-c", "/scripts/start_pgbackrest_api.sh"]
          volumeMounts:
            - name: postgres-pgsocket # use this with sidecar
              mountPath: /var/run/postgresql
            - name: postgres-data
              mountPath: /home/postgres/pgdata/data
            - name: postgres-config
              subPath: pgbackrest.conf
              mountPath: /home/postgres/pgdata/backup/pgbackrest.conf
            - name: postgres-config
              subPath: start_pgbackrest_api.sh
              mountPath: /scripts/start_pgbackrest_api.sh
      volumes:
        - name: postgres-pgsocket
          emptyDir: { }
  volumeClaimTemplates:
    - metadata:
        name: postgres-data
        namespace: postgres
      spec:
        accessModes:
          - ReadWriteOnce
        storageClassName: local-path
        resources:
          requests:
            storage: 50Gi
        volumeName: postgres-data
    - metadata:
        name:  postgres-config
        namespace: postgres
      spec:
        storageClassName: longhorn-single-replica
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 500Mi
        volumeName: postgres-config
