---
# Source: mqtt-connector/templates/deployment.yml
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    # Original Helm labels v
    app: release-name-mqtt-connector
    component: mqtt-connector
    chart: mqtt-connector-0.4.5
    heritage: Helm
    release: release-name
    # Helm/k8s recommended label names v
    app.kubernetes.io/name: release-name-mqtt-connector
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/version: 0.4.5
    app.kubernetes.io/component: mqtt-connector
    app.kubernetes.io/part-of: openfaas
    app.kubernetes.io/managed-by: Helm
    helm.sh/chart: mqtt-connector-0.4.5
  name: release-name-mqtt-connector
  namespace: "openfaas"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: release-name-mqtt-connector
      component: mqtt-connector

  template:
    metadata:
      annotations:
        prometheus.io/scrape: "false"
      labels:
        app: release-name-mqtt-connector
        component: mqtt-connector
    spec:
      volumes:
        - name: auth
          secret:
            secretName: basic-auth
      containers:
        - name: connector
          image: ghcr.io/openfaas/mqtt-connector:latest
          command:
          - "/usr/bin/mqtt-connector"
          args:
           - "-broker=tcp://192.168.0.201:1883"
           - "-topic=homeassistant/#"
           - "-id=mqttconnector"
          env:
            - name: gateway_url
              value: "http://192.168.0.203:8080"
            - name: print_response
              value: 
            - name: print_response_body
              value: 
            - name: content_type
              value: "application/json"
            - name: basic_auth
              value: "true"
            - name: secret_mount_path
              value: "/var/secrets"
            - name: upstream_timeout
              value: "30s"
            - name: rebuild_interval
              value: "15s"
          volumeMounts:
            - name: auth
              readOnly: true
              mountPath: "/var/secrets"
