apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: trilium-ole
  namespace: apps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: trilium-ole
  template:
    metadata:
      labels:
        app: trilium-ole
    spec: 
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/hostname
                    operator: In
                    values:
                      - master0
      containers:
        - name: trilium-ole
          image: triliumnext/trilium:latest
          ports:
            - containerPort: 8080 
          env:
            - name: TZ
              value: "Europe/Oslo"
          volumeMounts:
            - name: trilium-ole-data
              mountPath: /home/node/trilium-data 
      volumes:
        - name: trilium-ole-data
          persistentVolumeClaim:
            claimName: trilium-ole-data-pvc