log:
  level: info

api:
  listen: ":1984"

webrtc:
  # Allow external access
  listen: :8555
  allow_talk: true
  candidates:
    - go2rtc-webrtc.camera-bridge:8555

streams:
  entrance_roof: 
    - "ffmpeg:http://${CAMERA_ENTRANCE_ROOF_IP}/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=${CAMERA_ENTRANCE_ROOF_USER}&password=${CAMERA_ENTRANCE_ROOF_PASSWORD}#video=copy#audio=opus"
  entrance_roof_sub: 
    - "ffmpeg:http://${CAMERA_ENTRANCE_ROOF_IP}/flv?port=1935&app=bcs&stream=channel0_sub.bcs&user=${CAMERA_ENTRANCE_ROOF_USER}&password=${CAMERA_ENTRANCE_ROOF_PASSWORD}#video=copy#audio=opus"
  office: 
    - "ffmpeg:http://${CAMERA_OFFICE_IP}/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=${CAMERA_OFFICE_USER}&password=${CAMERA_OFFICE_PASSWORD}#video=copy#audio=opus"