apiVersion: apps/v1
kind: Deployment
metadata:
  name: go2rtc
  namespace: bridges
  labels:
    app: go2rtc
spec:
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: go2rtc
  template:
    metadata:
      labels:
        app: go2rtc
    spec: 
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/hostname
                    operator: In
                    values:
                      - master0
      containers:
        - name: go2rtc
          image: alexxit/go2rtc # :master-hardware support hardware transcoding for NVidia GPU
          ports:
            - containerPort: 1984 # Web UI/API
            - containerPort: 8554 # RTSP
            - containerPort: 8555 # WebRTC
          envFrom:
          - secretRef:
              name: go2rtc-secrets
          volumeMounts:
            - name: go2rtc-config
              mountPath: /config/go2rtc.yaml
              subPath: go2rtc.yaml
        - name: neolink
          image: quantumentangledandy/neolink
          ports:
            - containerPort: 9500 # Neolink web UI (adjust if needed) 
          volumeMounts:
            - name: neolink-config
              mountPath: /etc/neolink.toml
              subPath: config.toml 
          env:
            - name: TZ
              value: Europe/Oslo
      volumes:
        - name: go2rtc-config
          configMap:
            name: go2rtc-config 
        - name: neolink-config
          configMap:
            name: neolink-config 