apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: go2rtc-secrets
  namespace: bridges
spec:
  refreshInterval: "15s"
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  target:
    name: go2rtc-secrets
    creationPolicy: Owner
  data:
    - secretKey: CAMERA_ENTRANCE_ROOF_IP
      remoteRef:
        key: bridges/go2rtc
        property: CAMERA_ENTRANCE_ROOF_IP
    - secretKey: CAMERA_ENTRANCE_ROOF_USER
      remoteRef:
        key: bridges/go2rtc
        property: CAMERA_ENTRANCE_ROOF_USER
    - secretKey: CAMERA_ENTRANCE_ROOF_PASSWORD
      remoteRef:
        key: bridges/go2rtc
        property: CAMERA_ENTRANCE_ROOF_PASSWORD
    - secretKey: CAMERA_OFFICE_IP
      remoteRef:
        key: bridges/go2rtc
        property: CAMERA_OFFICE_IP
    - secretKey: CAMERA_OFFICE_USER
      remoteRef:
        key: bridges/go2rtc
        property: CAMERA_OFFICE_USER
    - secretKey: CAMERA_OFFICE_PASSWORD
      remoteRef:
        key: bridges/go2rtc
        property: CAMERA_OFFICE_PASSWORD