apiVersion: v1
kind: ConfigMap
metadata:
  name: bluetooth2kafka-schedules
  namespace: bridges
data:
  schedules.yaml: |
    scan:
      cron: "0 * * * *"
      kafka_topic: "scan"

    connect:
      - cron: "*/15 * * * *"
        address: "XX:XX:XX:XX:XX:01"
        manufacturer: "820"
      - cron: "*/15 * * * *"
        address: "XX:XX:XX:XX:XX:02"
        manufacturer: "820"
      - cron: "*/15 * * * *"
        address: "XX:XX:XX:XX:XX:03"
        manufacturer: "820"

    command:
      - cron: "0 0 * * *"
        address: "XX:XX:XX:XX:XX:01"
        manufacturer: "820"
        characteristic: "b42e2d06-ade7-11e4-89d3-123b93f75cba"
        command: "\x6d"
        format_type: "<L2BH2B9H"
      - cron: "0 0 * * *"
        address: "XX:XX:XX:XX:XX:02"
        manufacturer: "820"
        characteristic: "b42e2d06-ade7-11e4-89d3-123b93f75cba"
        command: "\x6d"
        format_type: "<L2BH2B9H"
      - cron: "0 0 * * *"
        address: "XX:XX:XX:XX:XX:01"
        manufacturer: "820"
        characteristic: "b42e2d06-ade7-11e4-89d3-123b93f75cba"
        command: "\x6d"
        format_type: "<L2BH2B9H"