apiVersion: v1
kind: Service
metadata: 
  name: flink-jobs-rest-public
  namespace: flink 
  labels:
    app: flink-jobs
    type: flink-native-kubernetes 
spec: 
  type: LoadBalancer 
  ports:
    - name: rest
      port: 8081
      protocol: TCP
      targetPort: 8081
  selector:
    app: flink-jobs
    component: jobmanager
    type: flink-native-kubernetes
  sessionAffinity: None