---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: diun-mqtt
  namespace: linole
  labels:
    app: diun-mqtt
spec:
  replicas: 1
  selector:
    matchLabels:
      app: diun-mqtt
  template:
    metadata:
      labels:
        app: diun-mqtt
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/hostname
                    operator: In
                    values:
                      - node0
      containers:
        - name: diun-mqtt
          image: crazymax/diun:latest
          env:
            - name: TZ
              value: "Europe/Paris"
            - name: LOG_LEVEL
              value: "info"
            - name: LOG_JSON
              value: "false"
          volumeMounts:
            - name: diun-mqtt-config
              mountPath: /etc/diun/diun.yaml
              subPath: diun.yaml
            - name: diun-mqtt-config
              mountPath: /etc/diun/image-watch.yaml
              subPath: image-watch.yaml
            - name: diun-mqtt-data
              mountPath: /data
      volumes:
        - name: diun-mqtt-config
          configMap:
            name: diun-mqtt-config
        - name: diun-mqtt-data
          hostPath:
            path: /home/ole/.diun