services: 

  gluetun-vpn:
    image: qmcgaw/gluetun
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    devices:
      - /dev/net/tun:/dev/net/tun
    volumes:
      - /lib/modules:/lib/modules:ro
    env_file:
      - ./torrent-stack.env
    ports:     
      - "8191:8191" # flaresolverr
      - "6881:6881" # qbittorrent
      - "6881:6881/udp" # qbittorrent
      - "8080:8080" # qbittorrent
      - "7878:7878" # radarr
      - "8989:8989" # sonarr
      - "8686:8686" # lidarr
      - "9117:9117" # jackett
      - "5055:5055" # jellyseerr

  qbittorrent:
    image: ghcr.io/linuxserver/qbittorrent
    network_mode: "service:gluetun-vpn"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Oslo
      - WEBUI_PORT=8080
    volumes:
      - /hdd/media/downloads:/downloads
      - /torrent/config/qbittorrent:/config 

  radarr:
    image: ghcr.io/linuxserver/radarr
    network_mode: "service:gluetun-vpn"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Oslo
    volumes:
      - /torrent/config/radarr:/config
      - /hdd/media/movies:/movies
      - /hdd/media/downloads:/downloads 

  sonarr:
    image: ghcr.io/linuxserver/sonarr
    network_mode: "service:gluetun-vpn"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Oslo
    volumes:
      - /torrent/config/sonarr:/config
      - /hdd/media/tv:/tv
      - /hdd/media/downloads:/downloads 

  lidarr:
    image: ghcr.io/linuxserver/lidarr
    network_mode: "service:gluetun-vpn"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Oslo
    volumes:
      - /torrent/config/lidarr:/config
      - /hdd/music/data:/music
      - /hdd/media/downloads:/downloads

  jackett:
    image: ghcr.io/linuxserver/jackett
    network_mode: "service:gluetun-vpn"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Oslo
    volumes:
      - /torrent/config/jackett:/config
      - /hdd/media/downloads:/downloads 

  jellyseerr:
    image: fallenbagel/jellyseerr:latest
    network_mode: "service:gluetun-vpn"
    environment:
      - LOG_LEVEL=info
      - TZ=Europe/Oslo
      - PORT=5055
    volumes:
      - /torrent/config/jellyseerr:/app/config

  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr
    network_mode: "service:gluetun-vpn" 
    environment:
      - LOG_LEVEL=debug
      - TZ=Europe/Oslo
      - HOST=0.0.0.0
      - PORT=8191
      - HEADLESS=true
      - BROWSER_TIMEOUT=55000