apiVersion: apps/v1
kind: Deployment
metadata:
  name: camera-agent
  namespace: camera-processors
  labels:
    app: camera-agent
spec:
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: camera-agent
  template:
    metadata:
      labels:
        app: camera-agent
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/hostname
                    operator: In
                    values:
                      - master0

      containers:
        - name: entrance-hallway
          image: ghcr.io/ole-klokkhammer/camera-agent:1.0.48
          securityContext:
            privileged: true # use if coral
          env:
            - name: LOG_LEVEL
              value: "info"
            - name: CAMERA_STREAM_URL
              value: "rtsp://go2rtc.camera-bridge:8554/entrance_roof"
            - name: ENABLE_VIDEO_RESTREAMER
              value: "false"
            - name: ENABLE_OBJECT_DETECTION
              value: "false"
          volumeMounts:
            - name: camera-agent-data
              subPath: entrance_roof
              mountPath: /data 
        - name: office
          image: ghcr.io/ole-klokkhammer/camera-agent:1.0.48
          securityContext:
            privileged: true # use if coral
          env:
            - name: LOG_LEVEL
              value: "info"
            - name: CAMERA_STREAM_URL
              value: "rtsp://go2rtc.camera-bridge:8554/office"
            - name: ENABLE_OBJECT_DETECTION
              value: "false"
            - name: ENABLE_VIDEO_RESTREAMER
              value: "false"
            - name: VIDEO_RESTREAMER_STREAM_URL
              value: "rtsp://127.0.0.1:8554/office_motion"
          volumeMounts:
            - name: camera-agent-data
              subPath: office
              mountPath: /data
              
        - name: go2rtc
          image: alexxit/go2rtc
          ports:
            - containerPort: 1984 # Web UI/API
            - containerPort: 8554 # RTSP
            - containerPort: 8555 # WebRTC
          volumeMounts:
            - name: go2rtc-config
              mountPath: /config/go2rtc.yaml
              subPath: go2rtc.yaml

      volumes:
        - name: camera-agent-data
          hostPath:
            path: /mnt/data/camera
        - name: go2rtc-config
          configMap:
            name: go2rtc-config 
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: go2rtc-config
  namespace: camera-processors
data:
  go2rtc.yaml: |
    streams:
      entrance_roof_motion:
        - rtsp://127.0.0.1:8554/entrance_roof_motion
      office_motion:
        - rtsp://127.0.0.1:8554/office_motion
    # Add more config as needed
