apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: bluetooth-api
  namespace: bluetooth
  labels:
    app: bluetooth-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bluetooth-api
  template:
    metadata:
      labels:
        app: bluetooth-api
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/hostname
                    operator: In
                    values:
                      - master0
      containers:
        - name: bluetooth-api
          image: olklokk/bluetooth-api:1.1.1
          ports:
            - containerPort: 8080
          env:
            - name: LOG_LEVEL
              value: "info"
            - name: API_PORT
              value: "8080"
          securityContext:
            capabilities:
              add:
                - NET_ADMIN
                - NET_RAW
            appArmorProfile:
              type: Unconfined
          volumeMounts:
            - mountPath: /var/run/dbus
              name: dbus-socket
      volumes:
        - name: dbus-socket
          hostPath:
            path: /var/run/dbus
            type: Directory