apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: homeassistant
  namespace: homeassistant
  labels:
    app: homeassistant
spec:
  replicas: 1
  serviceName: homeassistant
  selector:
    matchLabels:
      app: homeassistant
  template:
    metadata:
      namespace: homeassistant
      labels:
        app: homeassistant
    spec:
      containers:
        - name: homeassistant
          image: homeassistant/home-assistant:stable
          ports:
            - containerPort: 8123
          volumeMounts:
            - mountPath: /config
              name: homeassistant-data
  volumeClaimTemplates:
    - metadata:
        name: homeassistant-data
        namespace: homeassistant
      spec:
        storageClassName: longhorn-single-replica
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 500Mi
        volumeName: homeassistant-data
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: homeassistant-data
  namespace: homeassistant
  labels: 
    app: homeassistant
spec:
  storageClassName: longhorn-single-replica
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 500Mi
  volumeMode: Filesystem
  csi:
    driver: driver.longhorn.io
    fsType: ext4
    volumeHandle: homeassistant-data
    volumeAttributes:
      numberOfReplicas: "1"