apiVersion: v1
kind: Service
metadata:
  name: zigbee-mqtt
  namespace: linole
spec:
  type: LoadBalancer
  selector:
    app: zigbee-mqtt
  ports:
    - port: 8080
      targetPort: 8080
      name: http
  loadBalancerIP: 10.0.10.207