- id: '1626813141220'
  alias: Watering the plants at 09_00
  description: Lets water the plants in the morning
  trigger:
  - platform: time
    at: 09:00
    id: first time watering
  condition: []
  action:
  - service: switch.turn_on
    target:
      entity_id: switch.smartplug_switch
  - delay:
      hours: 0
      minutes: 1
      seconds: 0
      milliseconds: 0
  - service: switch.turn_off
    target:
      entity_id: switch.smartplug_switch
  mode: single
- id: '1626815391749'
  alias: Watering the plants at 21_00
  description: Lets water the plants in the evening
  trigger:
  - platform: time
    id: first time watering
    at: '21:00'
  condition: []
  action:
  - service: switch.turn_on
    target:
      entity_id: switch.smartplug_switch
  - delay:
      hours: 0
      minutes: 1
      seconds: 0
      milliseconds: 0
  - service: switch.turn_off
    target:
      entity_id: switch.smartplug_switch
  mode: single
- id: '1626815498877'
  alias: Watering the plants at 15_00
  description: Lets water the plants in the day
  trigger:
  - platform: time
    at: '15:00'
    id: first time watering
  condition: []
  action:
  - service: switch.turn_on
    target:
      entity_id: switch.smartplug_switch
  - delay:
      hours: 0
      minutes: 1
      seconds: 0
      milliseconds: 0
  - service: switch.turn_off
    target:
      entity_id: switch.smartplug_switch
  mode: single
- id: '1650116457484'
  alias: Purge database for events
  description: ''
  trigger:
  - platform: time_pattern
    hours: '00'
    minutes: '00'
    seconds: '00'
  condition: []
  action:
  - service: recorder.purge_entities
    data: {}
  mode: single
- id: '1650281064050'
  alias: diun
  description: ''
  trigger:
  - platform: mqtt
    topic: diun
  condition: []
  action:
  - service: notify.mobile_app_pixel_5
    data:
      message: 'Hello world '
  mode: single