custom_header:
  hide_header: true
  background: 'rgba(150, 150, 150, 0.3)'
  compact_mode: true


background: var(--background-image)

title: 'Linole'
views:
  - title: Home
    panel: true
    path: default_view
    badges: [ ]
    cards:
      - type: vertical-stack
        cards:
          - type: 'custom:clockwork-card'
            entity: sensor.date_time_iso
            locale: 'nb'
          - type: horizontal-stack
            cards:
              - type: weather-forecast
                entity: weather.home
          - type: horizontal-stack
            cards:
              - type: gauge
                theme: default
                entity: sensor.airthings_wave_plus_1_co2
                max: 2000
                min: 0
                name: CO2
                severity:
                  green: 0
                  red: 1000
                  yellow: 800
                unit: ppm
              - type: gauge
                entity: sensor.airthings_wave_plus_1_voc
                theme: default
                max: 2000
                min: 0
                name: VOC
                severity:
                  green: 0
                  red: 2000
                  yellow: 250
                unit: ppm
              - type: gauge
                entity: sensor.airthings_wave_plus_1_humidity
                theme: default
                name: Humidity
                min: 0
                max: 100
                severity:
                  green: 30
                  yellow: 29
                  red: 20
              - type: gauge
                entity: sensor.airthings_wave_plus_1_radon_long
                theme: default
                name: Radon Lt
                min: 0
                max: 300
                severity:
                  green: 0
                  yellow: 100
                  red: 150
              - type: gauge
                entity: sensor.apartment_temperature
                theme: default
                max: 50
                min: 0
                name: Linole
                severity:
                  green: 0
                  red: 30
                  yellow: 23
          - type: horizontal-stack
            cards:
              - type: vertical-stack
                cards:
                  - type: button
                    entity: light.all
                    icon: mdi:lightbulb-group
                    icon_height: "60px"
                  - type: horizontal-stack
                    cards:
                      - type: button
                        entity: light.bedroom
                        icon: mdi:lightbulb
                        icon_height: "40px"
                        hold_action:
                          action: more-info
                      - type: button
                        entity: light.livingroom
                        icon: mdi:lightbulb
                        icon_height: "40px"
                        hold_action:
                          action: more-info
                  - type: horizontal-stack
                    cards:
                      - type: button
                        entity: light.entrance
                        icon: mdi:lightbulb
                        hold_action:
                          action: more-info
                      - type: button
                        entity: light.kitchen
                        icon: mdi:lightbulb
                        hold_action:
                          action: more-info
                      - type: button
                        entity: light.garden
                        icon: mdi:lightbulb
                        hold_action:
                          action: more-info
              - type: button
                icon: 'mdi:exit-run'
                tap_action:
                  action: call-service
                  service: script.leave_apartment
          - type: horizontal-stack
            cards:
              - type: glance
                title: Dyson humidifier
                show_name: true
                show_icon: false
                show_state: true
                state_color: true
                columns: 3
                entities:
                  - entity: sensor.dyson_humidify_cool_humidity
                    name: Humidity
                  - entity: sensor.dyson_humidify_cool_temperature
                    name: Temperature
                  - entity: sensor.dyson_humidify_cool_voc
                    name: VOC
                  - entity: sensor.dyson_humidify_cool_pm2_5
                    name: PM 2.5
                  - entity: sensor.dyson_humidify_cool_pm10
                    name: PM 10
                  - entity: sensor.dyson_humidify_cool_nox
                    name: NOx
              - type: glance
                title: Dyson purifier
                show_name: true
                show_icon: false
                show_state: true
                state_color: true
                columns: 3
                entities:
                  - entity: sensor.dyson_hot_cool_humidity
                    name: Humidity
                  - entity: sensor.dyson_hot_cool_temperature
                    name: Temperature
                  - entity: sensor.dyson_hot_cool_voc
                    name: VOC
                  - entity: sensor.dyson_hot_cool_pm2_5
                    name: PM 2.5
                  - entity: sensor.dyson_hot_cool_pm10
                    name: PM 10
                  - entity: sensor.dyson_hot_cool_nox
                    name: NOx