

sensor:
  # main_bedroom
  - state_topic: airthings/2930018919/co2
    name: "airthings/main_bedroom/co2"
    unit_of_measurement: "ppm"
    icon: mdi:cloud
  - state_topic: airthings/2930018919/voc
    name: "airthings/main_bedroom/voc"
    unit_of_measurement: "ppb"
  - state_topic: airthings/2930018919/humidity
    name: "airthings/main_bedroom/humidity"
    unit_of_measurement: "%"
    device_class: humidity
  - state_topic: airthings/2930018919/radon_st_avg
    name: "airthings/main_bedroom/radon_short"
    unit_of_measurement: "Bq/m3"
    icon: mdi:cloud
  - state_topic: airthings/2930018919/radon_lt_avg
    name: "airthings/main_bedroom/radon_long"
    unit_of_measurement: "Bq/m3"
    icon: mdi:cloud
  - state_topic: airthings/2930018919/pressure
    name: "airthings/main_bedroom/pressure"
    unit_of_measurement: "mbar"
    device_class: pressure
    icon: mdi:gauge
  - state_topic: airthings/2930018919/temperature
    name: "airthings/main_bedroom/temperature"
    unit_of_measurement: "°C"
    device_class: temperature

# livingroom
  - state_topic: airthings/2930145104/co2
    name: "airthings/livingroom/co2"
    unit_of_measurement: "ppm"
    icon: mdi:cloud
  - state_topic: airthings/2930145104/voc
    name: "airthings/livingroom/voc"
    unit_of_measurement: "ppb"
  - state_topic: airthings/2930145104/humidity
    name: "airthings/livingroom/humidity"
    unit_of_measurement: "%"
    device_class: humidity
  - state_topic: airthings/2930145104/radon_st_avg
    name: "airthings/livingroom/radon_short"
    unit_of_measurement: "Bq/m3"
    icon: mdi:cloud
  - state_topic: airthings/2930145104/radon_lt_avg
    name: "airthings/livingroom/radon_long"
    unit_of_measurement: "Bq/m3"
    icon: mdi:cloud
  - state_topic: airthings/2930145104/pressure
    name: "airthings/livingroom/pressure"
    unit_of_measurement: "mbar"
    device_class: pressure
    icon: mdi:gauge
  - state_topic: airthings/2930145104/temperature
    name: "airthings/livingroom/temperature"
    unit_of_measurement: "°C"
    device_class: temperature

# basement
  - state_topic: airthings/2930151076/co2
    name: "airthings/basement/co2"
    unit_of_measurement: "ppm"
    icon: mdi:cloud
  - state_topic: airthings/2930151076/voc
    name: "airthings/basement/voc"
    unit_of_measurement: "ppb"
  - state_topic: airthings/2930151076/humidity
    name: "airthings/basement/humidity"
    unit_of_measurement: "%"
    device_class: humidity
  - state_topic: airthings/2930151076/radon_st_avg
    name: "airthings/basement/radon_short"
    unit_of_measurement: "Bq/m3"
    icon: mdi:cloud
  - state_topic: airthings/2930151076/radon_lt_avg
    name: "airthings/basement/radon_long"
    unit_of_measurement: "Bq/m3"
    icon: mdi:cloud
  - state_topic: airthings/2930151076/pressure
    name: "airthings/basement/pressure"
    unit_of_measurement: "mbar"
    device_class: pressure
    icon: mdi:gauge
  - state_topic: airthings/2930151076/temperature
    name: "airthings/basement/temperature"
    unit_of_measurement: "°C"
    device_class: temperature
