apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: bluetooth-sink-secrets
  namespace: processors
spec:
  refreshInterval: "15s"
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  target:
    name: bluetooth-sink-secrets 
  data:
  - secretKey: RABBITMQ_HOST
    remoteRef:
      key: rabbitmq
      property: RABBITMQ_HOST
  - secretKey: RABBITMQ_USER
    remoteRef:
      key: rabbitmq
      property: GUEST_RABBITMQ_USER
  - secretKey: RABBITMQ_PASSWORD
    remoteRef:
      key: rabbitmq
      property: GUEST_RABBITMQ_PASSWORD
  - secretKey: MQTT_HOST
    remoteRef:
      key: hivemq
      property: MQTT_HOST
  - secretKey: DB_HOST
    remoteRef:
      key: postgres
      property: DB_HOST
  - secretKey: DB_PORT
    remoteRef:
      key: postgres
      property: DB_PORT
  - secretKey: DB_USER
    remoteRef:
      key: postgres
      property: BLUETOOTH_DB_USER
  - secretKey: DB_PASSWORD
    remoteRef:
      key: postgres
      property: BLUETOOTH_DB_PASSWORD
