apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: huebridge-mqtt
  namespace: linole
spec:
  replicas: 1
  serviceName: huebridge-mqtt
  selector:
    matchLabels:
      app: huebridge-mqtt
  template:
    metadata:
      namespace: linole
      labels:
        app: huebridge-mqtt
    spec:
      hostNetwork: true
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/hostname
                    operator: In
                    values:
                      - node2
      containers:
        - name: huebridge-mqtt
          image: diyhue/core
          env:
            - name: MAC
              value: "e4:5f:01:4b:87:75" # node2
            - name: IP
              value: "192.168.10.102"  # node2
          volumeMounts:
            - name: huebridge-mqtt-config
              mountPath: /opt/hue-emulator/config
  volumeClaimTemplates:
    - metadata:
        name: huebridge-mqtt-config
        namespace: diyhue
      spec:
        accessModes: [ "ReadWriteOnce" ]
        storageClassName: "longhorn"
        resources:
          requests:
            storage: 50Mi