apiVersion: v1
kind: Service
metadata:
  name: huebridge-mqtt
  namespace: linole
spec:
  type: LoadBalancer
  selector:
    app: huebridge-mqtt
  ports:
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP
  loadBalancerIP: 192.168.0.204
---
#apiVersion: v1
#kind: Service
#metadata:
#  name: diyhue
#  namespace: diyhue
#spec:
#  type: NodePort
#  selector:
#    app: diyhue
#  ports:
#    - name: http
#      port: 80
#      targetPort: 80
#      protocol: TCP
#    - name: https
#      port: 443
#      targetPort: 443
#      protocol: TCP
#    - port: 1900
#      targetPort: 1900
#      name: udp1
#      protocol: UDP
#    - port: 2100
#      targetPort: 2100
#      name: udp2
#      protocol: UDP
#    - port: 1982
#      targetPort: 1982
#      name: udp3
#      protocol: UDP
#---