[versions]
hivemq-extension-sdk = "4.0.0"

[libraries]
kafka-client = { module = "org.apache.kafka:kafka-clients", version = "4.0.0" }

[plugins]
hivemq-extension = { id = "com.hivemq.extension", version = "3.2.0" }
license = { id = "com.github.hierynomus.license", version = "0.16.1" }
