apiVersion: v1
kind: Service
metadata:
  name: qbittorrent
  namespace: media
spec:
  type: LoadBalancer
  selector:
    app: torrent-stack
  ports:
    - port: 8080
      targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: sonarr
  namespace: media
spec:
  type: LoadBalancer
  selector:
    app: torrent-stack
  ports:
    - protocol: TCP
      port: 8989
      targetPort: 8989
---
apiVersion: v1
kind: Service
metadata:
  name: radarr
  namespace: media
spec:
  type: LoadBalancer
  selector:
    app: torrent-stack
  ports:
    - protocol: TCP
      port: 7878
      targetPort: 7878
---
apiVersion: v1
kind: Service
metadata:
  name: jackett
  namespace: media
spec:
  type: LoadBalancer
  selector:
    app: torrent-stack
  ports:
    - protocol: TCP
      port: 9117
      targetPort: 9117
---

---
apiVersion: v1
kind: Service
metadata:
  name: jellyseerr
  namespace: media
spec:
  type: LoadBalancer
  selector:
    app: torrent-stack
  ports:
    - port: 5055
      targetPort: 5055
      nodePort: 30555
---
apiVersion: v1
kind: Service
metadata:
  name: lidarr
  namespace: media
spec:
  type: LoadBalancer
  selector:
    app: torrent-stack
  ports:
    - port: 8686
      targetPort: 8686
