apiVersion: apps/v1
kind: Deployment
metadata:
  name: go2rtc
  namespace: go2rtc
  labels:
    app: go2rtc
spec:
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: go2rtc
  template:
    metadata:
      labels:
        app: go2rtc
    spec: 
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/hostname
                    operator: In
                    values:
                      - master0
      containers:
        - name: go2rtc
          image: alexxit/go2rtc # :master-hardware support hardware transcoding for NVidia GPU
          ports:
            - containerPort: 1984 # Web UI/API
            - containerPort: 8554 # RTSP
            - containerPort: 8555 # WebRTC
          env: 
            - name: CAMERA_ENTRANCE_ROOF_IP
              valueFrom:
                secretKeyRef:
                  name: go2rtc-secrets
                  key: CAMERA_ENTRANCE_ROOF_IP
            - name: CAMERA_ENTRANCE_ROOF_USER
              valueFrom:
                secretKeyRef:
                  name: go2rtc-secrets
                  key: CAMERA_ENTRANCE_ROOF_USER
            - name: CAMERA_ENTRANCE_ROOF_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: go2rtc-secrets
                  key: CAMERA_ENTRANCE_ROOF_PASSWORD
          volumeMounts:
            - name: go2rtc-config
              mountPath: /config/go2rtc.yaml
              subPath: go2rtc.yaml
      volumes:
        - name: go2rtc-config
          configMap:
            name: go2rtc-config

---
# - "ffmpeg:http://${CAMERA_ENTRANCE_ROOF_IP}/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=${CAMERA_ENTRANCE_ROOF_USER}&password=${CAMERA_ENTRANCE_ROOF_PASSWORD}#video=copy#audio=copy#audio=opus"
apiVersion: v1
kind: ConfigMap
metadata:
  name: go2rtc-config
  namespace: go2rtc
data:
  go2rtc.yaml: |
    log:
      level: info
 
    webrtc:
      # Allow external access
      listen: :8555
      candidates:
        - go2rtc-webrtc.go2rtc:8555

    streams:
      entrance_roof: 
        - "ffmpeg:http://${CAMERA_ENTRANCE_ROOF_IP}/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=${CAMERA_ENTRANCE_ROOF_USER}&password=${CAMERA_ENTRANCE_ROOF_PASSWORD}#video=copy#audio=copy"
      entrance_roof_onvif: 
        - "onvif://${CAMERA_ENTRANCE_ROOF_USER}:${CAMERA_ENTRANCE_ROOF_PASSWORD}@${CAMERA_ENTRANCE_ROOF_IP}:8000"
      entrance_roof_sub: 
        - "ffmpeg:http://${CAMERA_ENTRANCE_ROOF_IP}/flv?port=1935&app=bcs&stream=channel0_sub.bcs&user=${CAMERA_ENTRANCE_ROOF_USER}&password=${CAMERA_ENTRANCE_ROOF_PASSWORD}#video=copy#audio=copy"