apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: nodered
  namespace: linole
  labels:
    app: nodered
spec:
  replicas: 1
  serviceName: nodered
  selector:
    matchLabels:
      app: nodered
  template:
    metadata:
      namespace: linole
      labels:
        app: nodered
    spec:
      containers:
        - name: nodered
          image: nodered/node-red
          ports:
            - containerPort: 1880
          volumeMounts:
            - mountPath: /data
              name: nodered-data
  volumeClaimTemplates:
    - metadata:
        name: nodered-data
        namespace: linole
      spec:
        storageClassName: longhorn-single-replica
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
        volumeName: nodered-data
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nodered-data
  namespace: linole
  labels:
    app: nodered
spec:
  storageClassName: longhorn-single-replica
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  csi:
    driver: driver.longhorn.io
    fsType: ext4
    volumeHandle: nodered-data
    volumeAttributes:
      numberOfReplicas: "1"