apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: llama-api
  namespace: apis
  labels:
    app: llama-api
spec:
  replicas: 1
  serviceName: llama-api
  selector:
    matchLabels:
      app: llama-api
  template:
    metadata:
      labels:
        app: llama-api
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/hostname
                    operator: In
                    values:
                      - master0
      initContainers:
        - name: check-fs-mount
          image: busybox
          command:
            [
              "sh",
              "-c",
              'test -f /fs/.mounted || (echo "File mount missing" && exit 1)',
            ]
          volumeMounts:
            - mountPath: /fs
              name: llama-data
      containers:
        - name: llama-api
          securityContext:
            privileged: true 
          image: ghcr.io/ole-klokkhammer/llama-api:1.0.25
          command: [
              "/app/llama-server",
              "--hf-repo",
              "xtuner/llava-llama-3-8b-v1_1-gguf",
              "--hf-file",
              "llava-llama-3-8b-v1_1-int4.gguf",
              "--port",
              "8080",
              "-n",
              "400",
              "-c",
              "4096", # context window size
              "-e",
              "-ngl",
              "33", # offload all layers to GPU
            ]
          ports:
            - containerPort: 8080
              name: http
          volumeMounts:
            - name: llama-data
              mountPath: /models
            - name: renderd128
              mountPath: /dev/dri/renderD128 # Vulkan device
            - name: card1
              mountPath: /dev/dri/card1 # Vulkan device
      volumes:
        - name: llama-data
          persistentVolumeClaim:
            claimName: llama-data-pvc
        - name: renderd128
          hostPath:
            path: /dev/dri/renderD128
            type: CharDevice
        - name: card1
          hostPath:
            path: /dev/dri/card1
            type: CharDevice
