version: "3.8"
services: 

  qbittorrent:
    image: ghcr.io/linuxserver/qbittorrent
    network_mode: "host"
    ports:
      - "6881:6881" # qbittorrent
      - "6881:6881/udp" # qbittorrent
      - "8080:8080" # qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - /hdd/media/downloads:/downloads
      - /config/qbittorrent:/config 

  radarr:
    image: ghcr.io/linuxserver/radarr
    network_mode: "host"
    ports: 
      - "7878:7878" # radarr
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - /config/radarr:/config
      - /hdd/media/movies:/movies
      - /hdd/media/downloads:/downloads 

  sonarr:
    image: ghcr.io/linuxserver/sonarr
    network_mode: "host"
    ports:  
      - "8989:8989" # sonarr
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - /config/sonarr:/config
      - /hdd/media/tv:/tv
      - /hdd/media/downloads:/downloads 

  lidarr:
    image: ghcr.io/linuxserver/lidarr
    network_mode: "host"
    ports:   
      - "8686:8686" # lidarr
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - /config/lidarr:/config
      - /hdd/music:/music
      - /hdd/media/downloads:/downloads
    security_opt:
      - apparmor:unconfined

  jackett:
    image: ghcr.io/linuxserver/jackett
    network_mode: "host"
    ports:    
      - "9117:9117" # jackett
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - /config/jackett:/config
      - /hdd/media/downloads:/downloads 

  jellyseerr:
    image: fallenbagel/jellyseerr:latest
    network_mode: "host"
    ports:      
      - "5055:5055" # jellyseerr
    environment:
      - LOG_LEVEL=info
      - TZ=Europe/Oslo
      - PORT=5055
    volumes:
      - /config/jellyseerr:/app/config
    security_opt:
      - apparmor:unconfined

  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr:v3.3.16 
    network_mode: "host"
    ports:     
      - "8191:8191" # flaresolverr
    environment:
      - LOG_LEVEL=debug
      - TZ=Europe/Oslo
      - HOST=0.0.0.0
      - PORT=8191
      - HEADLESS=true
      - BROWSER_TIMEOUT=55000 