apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: homeassistant
  namespace: apps
  labels:
    app: homeassistant
spec:
  replicas: 1
  revisionHistoryLimit: 0
  serviceName: homeassistant
  selector:
    matchLabels:
      app: homeassistant
  template:
    metadata:
      namespace: apps
      labels:
        app: homeassistant
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/hostname
                    operator: In
                    values:
                      - master0 
      initContainers:
        - name: check-fs-mount
          image: busybox
          command: ['sh', '-c', 'test -f /fs/.mounted || (echo "File mount missing" && exit 1)']
          volumeMounts:
            - mountPath: /fs
              name: homeassistant-data
      containers:
        - name: homeassistant
          image: homeassistant/home-assistant:stable
          ports:
            - containerPort: 8123
          volumeMounts:
            - mountPath: /config
              name: homeassistant-data 
          env:
            - name: HA_DB_URL
              valueFrom:
                secretKeyRef:
                  name: homeassistant-secrets
                  key: recorder_url
      volumes:
        - name: homeassistant-data
          persistentVolumeClaim:
            claimName: homeassistant-data-pvc 