apiVersion: v1
kind: Pod
metadata:
  name: bluetooth-api
  namespace: linole
  labels:
    app: bluetooth-api
spec:
  hostNetwork: true
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                  - master0
  containers:
    - name: bluetooth-api
      image: olklokk/bluetooth-api:latest
      securityContext:
        capabilities:
          add:
            - NET_ADMIN
            - NET_RAW
