apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  name: rabbitmq
  namespace: rabbitmq
spec:
  replicas: 1
  rabbitmq:
    additionalPlugins:
      - rabbitmq_management
      - rabbitmq_mqtt
      - rabbitmq_stream
    additionalConfig: |
      mqtt.allow_anonymous  = true
    envConfig: |
      RABBITMQ_DEFAULT_USER=admin
      RABBITMQ_DEFAULT_PASS=admin
      RABBITMQ_FEATURE_FLAGS="khepri_db"
  persistence:
    storage: 0
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                  - master0