apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-public
  namespace: rabbitmq
  labels:
    app.kubernetes.io/part-of: rabbitmq
    app.kubernetes.io/name: rabbitmq
    app.kubernetes.io/component: rabbitmq
spec:
  selector:
    app.kubernetes.io/name: rabbitmq
  type: LoadBalancer
  ports:
    - name: mqtt
      port: 1883
      targetPort: 1883
    - name: management-ui
      port: 15672
      targetPort: 15672