apiVersion: apps/v1
kind: Deployment
metadata:
  name: motion-detector
  namespace: camera-processors
  labels:
    app: motion-detector
spec:
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: motion-detector
  template:
    metadata:
      labels:
        app: motion-detector
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms: 
              - matchExpressions:
                  - key: kubernetes.io/hostname
                    operator: In
                    values:
                      - master0
      containers:
        - name: motion-detector
          image: olklokk/motion-detector:1.0.28
          securityContext:
            privileged: true # use if coral
          env: 
            - name: LOG_LEVEL
              value: "info" 
            - name: ENABLE_RESTREAMER
              value: "False" 
            - name: ENABLE_OBJECT_DETECTION
              value: "False" 
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: "kafka-kafka-bootstrap.kafka:9092" 
            - name: KAFKA_TOPIC
              value: "camera_frames" 
            - name: ENTRANCE_ROOF_STREAM_URL
              value: "rtsp://go2rtc.camera-bridge:8554/entrance_roof"
        - name: rtsp-server
          image: bluenviron/mediamtx:latest  
          ports:
            - containerPort: 8554
              name: rtsp-udp
              protocol: UDP
            - containerPort: 8554
              name: rtsp-tcp
              protocol: TCP