apiVersion: apps/v1
kind: Deployment
metadata:
  name: motion-detector
  namespace: camera-processors
  labels:
    app: motion-detector
spec:
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: motion-detector
  template:
    metadata:
      labels:
        app: motion-detector
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/hostname
                    operator: In
                    values:
                      - master0
      containers:
        - name: motion-detector
          image: olklokk/motion-detector:1.0.11
          env: 
            - name: LOG_LEVEL
              value: "info" 
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: "kafka-kafka-bootstrap.kafka:9092" 
            - name: ENTRANCE_ROOF_STREAM_URL
              value: "rtsp://go2rtc.go2rtc:8554/entrance_roof" 