services:
  anythingllm:
    image: mintplexlabs/anythingllm:pg
    container_name: anythingllm
    restart: unless-stopped
    network_mode: "host"
    cap_add:
      - SYS_ADMIN # to use anythingllm browser-based scraping features
    env_file:
      - .env
    environment:
      JWT_SECRET: ${JWT_SECRET}
      STORAGE_DIR: /app/server/storage
      DATABASE_URL: ${DATABASE_URL}
      PGVECTOR_CONNECTION_STRING: ${DATABASE_URL}
      VECTOR_DB: pgvector
    volumes:
      - /app/server/storage:/app/server/storage