config: {}
networks: [] # Keep this empty

storage_pools:
- name: default
  driver: btrfs
  description: ""
  config:
    source: /dev/ubuntu-vg/lxd-storage

profiles:
- config: {}
  description: ""
  devices:
    eth0:
      name: eth0
      nictype: bridged  # Use this for system bridges
      parent: br0       # The name of your Netplan bridge
      type: nic
    root:
      path: /
      pool: default
      type: disk
  name: default

projects: []
cluster: null