apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis
  namespace: redis
  labels:
    app: redis
spec:
  replicas: 1
  serviceName: redis
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/hostname
                    operator: In
                    values:
                      - master0 
      containers:
      - image: redis:alpine
        name: redis
        ports:
          - containerPort: 6379
        volumeMounts:
          - name: redis-data
            mountPath: /opt/redis/data
  volumeClaimTemplates:
    - metadata:
        name: redis-data
        namespace: redis
      spec:
        accessModes:
          - ReadWriteOnce
        storageClassName: local-path
        resources:
          requests:
            storage: 500Mi
        volumeName: redis-data
---
