apiVersion: v1
kind: PersistentVolume
metadata:
  name: redis-data
  namespace: redis
  labels:
    app: redis
spec:
  storageClassName: local-path
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - master0
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 500Mi
  local:
    path: /var/lib/redis
