apiVersion: apps/v1
kind: Deployment
metadata:
  name: mosquitto
  namespace: linole
  labels:
    app: mosquitto
spec:
  replicas: 1

  selector:
    matchLabels:
      app: mosquitto
  template:
    metadata:
      namespace: linole
      labels:
        app: mosquitto
    spec:
      containers:
        - name: mosquitto
          image: eclipse-mosquitto:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 1883
              name: tcp
          volumeMounts:
            - name: mosquitto-config
              mountPath: /mosquitto/config/mosquitto.conf
              subPath: mosquitto.conf
      volumes:
        - name: mosquitto-config
          configMap:
            name: mosquitto-config