apiVersion: v1
kind: Service
metadata:
  name: hivemq-external
  namespace: hivemq
  labels:
    app: hivemq
spec:
  type: LoadBalancer
  ports:
    - port: 1883
      targetPort: 1883
  selector:
    app: hivemq
---