# https://github.com/AlexxIT/go2rtc?tab=readme-ov-file#source-ffmpeg
# https://shotstack.io/learn/ffmpeg-blur-video/
# https://docs.frigate.video/configuration/
# https://docs.frigate.video/configuration/reference

logger:
  # Optional: default log level (default: shown below)
  default: info
  # Optional: module by module log level configuration
  logs:
    frigate.mqtt: error
    frigate.detectors: debug

mqtt:
  host: hivemq-internal.hivemq
  port: 1883

detectors:
  #  tensorrt: # requires tensorrt image
  #    type: tensorrt
  coral:
    type: edgetpu
    device: usb

#model:
#  path: /config/model_cache/tensorrt/yolov7-320.trt
#  input_tensor: nchw
#  input_pixel_format: rgb
#  width: 320
#  height: 320

ffmpeg:
  hwaccel_args: preset-nvidia

# https://stackoverflow.com/questions/53518589/how-to-use-filtering-and-stream-copy-together-with-ffmpeg#53526514
# https://docs.frigate.video/configuration/camera_specific/#reolink-cameras
go2rtc:
  streams:
    entrance_roof:
      - "ffmpeg:http://{FRIGATE_ENTRANCE_ROOF_IP}/flv?port=1935&app=bcs&stream=channel0_main.bcs&user={FRIGATE_REOLINK_USER}&password={FRIGATE_REOLINK_PASSWORD}#video=copy#audio=copy#audio=opus"
    entrance_roof_sub:
      - "ffmpeg:http://{FRIGATE_ENTRANCE_ROOF_IP}/flv?port=1935&app=bcs&stream=channel0_sub.bcs&user={FRIGATE_REOLINK_USER}&password={FRIGATE_REOLINK_PASSWORD}"
  webrtc:
    # Allow external access
    listen: :8555
    candidates:
      - frigate-webrtc.linole:8555

record:
  enabled: True
  retain:
    days: 7
    mode: motion
  alerts:
    retain:
      days: 30
  detections:
    retain:
      days: 30

snapshots:
  enabled: True
  bounding_box: True
  retain:
    default: 30

#video=h264#hardware#raw=-filter_complex "[0:v]crop=450:400:1470:700,boxblur=30[mask];[0:v][mask]overlay=1470:700[v]" -map "[v]"
cameras:
  # https://docs.frigate.video/configuration/camera_specific/
  entrance_roof:
    live:
      stream_name: entrance_roof
    detect:
      fps: 5
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/entrance_roof
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/entrance_roof_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
            - audio

birdseye:
  enabled: True
  mode: continuous

objects:
  track:
    - person
    - cat
    - car

review:
  alerts:
    labels:
      - car
      - person

version: 0.15-1