apiVersion: v1
kind: Service
metadata:
  name: frigate
  namespace: linole
spec:
  type: LoadBalancer
  selector:
    app: frigate
  ports:
    - port: 8971
      targetPort: 8971
---
apiVersion: v1
kind: Service
metadata:
  name: frigate-internal
  namespace: linole
  labels:
    app: frigate
spec:
  type: NodePort
  ports:
    - port: 5000
      targetPort: 5000
      name: tcp
  selector:
    app: frigate
---
apiVersion: v1
kind: Service
metadata:
  name: frigate-webrtc
  namespace: linole
  labels:
    app: frigate
spec:
  type: NodePort
  ports:
    - port: 8555
      targetPort: 8555
      name: tcp
      protocol: TCP
    - port: 8555
      targetPort: 8555
      name: udp
      protocol: UDP
  selector:
    app: frigate