apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: neo-secrets
  namespace: apps
spec:
  refreshInterval: "15s"
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  target:
    name: neo-secrets
  data:
    - secretKey: KC_HOSTNAME
      remoteRef:
        key: apps/neo
        property: KC_HOSTNAME
    - secretKey: AUTH_URL
      remoteRef:
        key: apps/neo
        property: AUTH_URL
    - secretKey: AUTH_SECRET
      remoteRef:
        key: apps/neo
        property: AUTH_SECRET
    - secretKey: KEYCLOAK_CLIENT_ID
      remoteRef:
        key: apps/neo
        property: KEYCLOAK_CLIENT_ID
    - secretKey: KEYCLOAK_CLIENT_SECRET
      remoteRef:
        key: apps/neo
        property: KEYCLOAK_CLIENT_SECRET
    - secretKey: KEYCLOAK_ISSUER
      remoteRef:
        key: apps/neo
        property: KEYCLOAK_ISSUER
    - secretKey: KEYCLOAK_MOBILE_CLIENT_ID
      remoteRef:
        key: apps/neo
        property: KEYCLOAK_MOBILE_CLIENT_ID
    - secretKey: KEYCLOAK_MOBILE_CLIENT_SECRET
      remoteRef:
        key: apps/neo
        property: KEYCLOAK_MOBILE_CLIENT_SECRET
    - secretKey: KEYCLOAK_MOBILE_AUTHORIZE_ENDPOINT
      remoteRef:
        key: apps/neo
        property: KEYCLOAK_MOBILE_AUTHORIZE_ENDPOINT
    - secretKey: KEYCLOAK_MOBILE_TOKEN_ENDPOINT
      remoteRef:
        key: apps/neo
        property: KEYCLOAK_MOBILE_TOKEN_ENDPOINT