apiVersion: v1
kind: Service
metadata:
  name: bluetooth-api
  namespace: linole
spec:
  type: ClusterIP
  selector:
    app: bluetooth-api
  ports:
    - port: 8080
      targetPort: 8080
      name: http
---
apiVersion: v1
kind: Service
metadata:
  name: bluetooth-api-external
  namespace: linole
spec:
  type: LoadBalancer
  selector:
    app: bluetooth-api
  ports:
    - port: 8080
      targetPort: 8080
      name: http