apiVersion: v1
kind: Service
metadata:
  name: otel-collector
  labels:
    app: opentelemetry
    component: otel-collector
spec:
  ports:
    - name: metrics # Default endpoint for querying metrics.
      port: 8888
  selector:
    component: otel-collector