# test-dns.yaml
apiVersion: v1
kind: Pod
metadata:
  name: dns-test
  labels:
    app: dns-test
spec:
  containers:
    - name: busybox
      image: busybox
      command: ['sleep', '3600']
---
apiVersion: v1
kind: Service
metadata:
  name: my-service
spec:
  selector:
    app: dns-test
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80