apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: hivemq
  namespace: hivemq
  labels:
    app: hivemq
spec:
  replicas: 1
  serviceName: hivemq
  selector:
    matchLabels:
      app: hivemq
  template:
    metadata:
      labels:
        app: hivemq
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/hostname
                    operator: In
                    values:
                      - master0
      containers:
        - name: hivemq
          image: hivemq/hivemq-ce:latest
          env:
            - name: HIVEMQ_PERSISTENCE_MODE
              value: "in-memory"
            - name: HIVEMQ_WEBSOCKET_ENABLED
              value: "true"
            - name: HIVEMQ_WEBSOCKET_PORT
              value: "8000"
            - name: HIVEMQ_WEBSOCKET_PATH
              value: "/mqtt"
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: "kafka-kafka-bootstrap.kafka:9092"
            - name: KAFKA_TOPIC
              value: "hivemq"
          ports:
            - containerPort: 1883
              name: mqtt
            - containerPort: 8000
              name: websocket
          volumeMounts:
            - name: hivemq-extensions
              mountPath: /opt/hivemq/extensions
            - name: hivemq-config
              subPath: config.xml
              mountPath: /opt/hivemq/conf/config.xml
      volumes:
        - name: hivemq-config
          configMap:
            name: hivemq-config
  volumeClaimTemplates:
    - metadata:
        name: hivemq-extensions
        namespace: hivemq
      spec:
        accessModes:
          - ReadWriteOnce
        storageClassName: local-path
        resources:
          requests:
            storage: 500Mi
        volumeName: hivemq-extensions