---
apiVersion: v1
kind: ConfigMap
metadata:
  name: hivemq-config
  namespace: hivemq
data:
  config.xml: |
    <?xml version="1.0"?>
    <hivemq>
        <listeners>
            <tcp-listener>
                <port>1883</port>
                <bind-address>0.0.0.0</bind-address>
            </tcp-listener>
            <websocket-listener>
                <port>8000</port>
                <bind-address>0.0.0.0</bind-address>
                <path>/mqtt</path>
                <name>my-websocket-listener</name>
                <subprotocols>
                    <subprotocol>mqttv3.1</subprotocol>
                    <subprotocol>mqtt</subprotocol>
                </subprotocols>
                <allow-extensions>true</allow-extensions>
            </websocket-listener>
        </listeners>
        <persistence>
            <mode>${HIVEMQ_PERSISTENCE_MODE}</mode>
        </persistence>
    </hivemq>
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: hivemq-data
  namespace: hivemq
  labels:
    app: hivemq
spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 500Mi
  local:
    path: /var/lib/hivemq
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - master0
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hivemq-data-pvc
  namespace: hivemq
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 500Mi
  volumeName: hivemq-data