
apiVersion: apps/v1
kind: Deployment
metadata:
  name: donetick
  namespace: apps
spec:
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: donetick
  template:
    metadata:
      labels:
        app: donetick
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/hostname
                    operator: In
                    values:
                      - master0
      containers: 
        - name: donetick
          image: donetick/donetick:latest
          ports:
            - containerPort: 2021 
          env:
            - name: DT_ENV
              value: "selfhosted"
            - name: DT_SERVER_CORS__ALLOW__ORIGINS
              value: "*"
            - name: DT_DATABASE_TYPE
              value: "postgres"
            - name: DT_DATABASE_HOST
              value: "postgres.postgres-external"
            - name: DT_DATABASE_PORT
              value: "5432"
            - name: DT_DATABASE_NAME
              value: "donetick"
            - name: DT_DATABASE_USER
              valueFrom:
                secretKeyRef:
                  name: donetick-secrets
                  key: DT_DATABASE_USER
            - name: DT_DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: donetick-secrets
                  key: DT_DATABASE_PASSWORD
            # Authentication
            - name: DT_JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: donetick-secrets
                  key: DT_JWT_SECRET
            - name: DT_AUTH_LOCAL_ENABLED
              value: "false"
            - name: DT_IS_USER_CREATION_DISABLED
              value: "true"
            - name: DT_OAUTH2_NAME
              value: "Keycloak"
            - name: DT_OAUTH2_CLIENT_ID
              value: "donetick"
            - name: DT_OAUTH2_CLIENT_SECRET
              value: "mthECymfjtj4sETxPMW0HwNNlUvcwiho"
            - name: DT_OAUTH2_REDIRECT_URL
              value: "https://tasks.linole.org/auth/oauth2"
            - name: DT_OAUTH2_SCOPES
              value: "openid profile email"
            - name: DT_OAUTH2_AUTH_URL
              value: "https://auth.linole.org/realms/master/protocol/openid-connect/auth"
            - name: DT_OAUTH2_TOKEN_URL
              value: "https://auth.linole.org/realms/master/protocol/openid-connect/token"
            - name: DT_OAUTH2_USER_INFO_URL
              value: "https://auth.linole.org/realms/master/protocol/openid-connect/userinfo"